export const CHILDREN_FORTUNE_V1 = {
  ruleVersion:"children-fortune-v1",bondVersion:"children-bond-v1",countTendencyVersion:"children-count-tendency-v1",
  genderEnergyVersion:"children-gender-energy-v1",parentingStyleVersion:"parenting-style-v1",periodActivationVersion:"children-period-activation-v1",
  outputPresenceSaturationPercent:40,
  outputPresenceWeights:{native:.40,adjusted:.60},
  hiddenWeights:{mainQi:1,middleQi:.5,residualQi:.25},hourPositionMultiplier:1.5,visibleOutputWeight:10,hourVisibleBonus:10,
  bondWeights:{outputPresence:.25,outputRootAvailability:.10,hourOutput:.25,hourStage:.15,usefulAlignment:.15,relationSalience:.10},relationSaliencePerRelation:20,
  countWeights:{outputPresence:.35,outputRootAvailability:.15,hourOutput:.30,hourStage:.20},
  countThresholds:{multiple:70,oneToTwo:50,oneCentered:30},bondThresholds:{veryStrong:75,strong:55,moderate:35},
  countConfidence:{highHourOutput:40,minimumAdjustedPresence:0},
  balancedGenderMargin:10,genderConfidence:{high:4,medium:2},
  stageSalience:{장생:85,목욕:65,관대:75,건록:90,제왕:100,쇠:60,병:40,사:30,묘:35,절:20,태:70,양:80} as Record<string,number>,
  parenting:{minimumClearScore:35,mixedMargin:10,supportiveCombinedMinimum:50},
  periodWeights:{existingActivation:.35,outputFlow:.30,hourRelationActivation:.20,relevantElementShare:.15},
  activationThresholds:{veryHigh:50,high:30,moderate:15},
  periodThemeThresholds:{highOutputFlow:50,highActivation:50},
  genderTradition:{sonTenGod:"식신",daughterTenGod:"상관",schoolPolicy:"POSTPOST_CUSTOM_CONSERVATIVE_V1"},
  countLabels:{LOW_CONNECTION:"자녀 인연이 넓게 퍼지기보다 선택적으로 나타나는 편",ONE_CHILD_CENTERED:"한 명과의 인연이 중심이 되기 쉬운 편",ONE_TO_TWO:"한두 명 정도로 자녀 인연이 이어지는 흐름",MULTIPLE_TENDENCY:"자녀 인연의 폭이 비교적 넓게 나타나는 편"},
} as const;
