import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { renderCalibrationTraceHtml } from "@/lib/saju/audit/html-renderer";
import { reconstructAnalysis } from "@/lib/saju/audit/reconstruction";
import { buildCalibrationSummary, buildSummaryTable } from "@/lib/saju/audit/summary";
import { buildCalibrationTrace, stableTraceJson } from "@/lib/saju/audit/trace-builder";
import { calculateSaju } from "@/lib/saju/engine";
import type { FortuneResult } from "@/types/fortune";
import { SYNTHETIC_INPUT } from "./synthetic-input";

const analysis=calculateSaju(SYNTHETIC_INPUT);
const trace=()=>buildCalibrationTrace(analysis,{caseId:"SYNTHETIC-TRACE-001",synthetic:true,relationshipStatus:"SINGLE"});
const expectedSteps=["INPUT_NORMALIZATION","LEGAL_BIRTH_DATETIME","ABSOLUTE_BIRTH_INSTANT","KOREAN_NATURAL_TIME","YEAR_PILLAR","MONTH_PILLAR","DAY_PILLAR","HOUR_PILLAR","HIDDEN_STEMS","TEN_GODS","TWELVE_STAGES","NATIVE_FIVE_ELEMENTS","SEASON_ADJUSTMENT","RELATIONS","TRANSFORMATION","ADJUSTED_FIVE_ELEMENTS","ROOT_DAMAGE","STRENGTH","STRUCTURE","STRUCTURE_QUALITY","SPECIAL_STRUCTURE","ADJUSTED_DAY_MASTER_STRENGTH","EOKBU","JOHU","TONGGWAN","BYEONGYAK","STRUCTURE_USEFUL_GOD","USEFUL_GOD_SYNTHESIS","STEM_PREFERENCES","BRANCH_PREFERENCES","STARS","DAEUN_GENERATION","DAEUN_ACTIVATION","SEUN","WOLUN","FORTUNE_TRANSFORMATION","FORTUNE_SYNTHESIS","CATEGORY_FORTUNE","WELLNESS","CHILDREN_FORTUNE","LIFETIME_GENERAL_INPUT"];

describe("CALIBRATION_TRACE_V1",()=>{
  it("emits the complete ordered 41-step pipeline with fact checks first",()=>{const value=trace();expect(value.steps).toHaveLength(41);expect(value.steps.map(row=>row.id)).toEqual(expectedSteps);expect(value.steps.slice(0,11).every(row=>row.index<=11)).toBe(true);});
  it("is stable for the same deterministic input",()=>expect(stableTraceJson(trace())).toBe(stableTraceJson(trace())));
  it("redacts personal fields by default while retaining an explicit private mode",()=>{const safe=trace();expect(JSON.stringify(safe.steps[0])).not.toContain(SYNTHETIC_INPUT.birthDate);expect(safe.privacy).toEqual({sensitiveInputIncluded:false,repositorySafe:true});const privateTrace=buildCalibrationTrace(analysis,{caseId:"CASE-001",includeSensitiveInput:true});expect(JSON.stringify(privateTrace.steps[0])).toContain(SYNTHETIC_INPUT.birthDate);expect(privateTrace.privacy.repositorySafe).toBe(false);});
  it("reconstructs every critical score exposed by v1 evidence",()=>{const checks=reconstructAnalysis(analysis),failed=checks.filter(row=>row.status==="FAIL");expect(checks.length).toBeGreaterThan(1000);expect(failed).toEqual([]);expect(checks.some(row=>row.id==="ELEMENT:CONSERVATION")).toBe(true);expect(checks.some(row=>row.id==="STRENGTH:FINAL")).toBe(true);expect(checks.some(row=>row.id.startsWith("USEFUL:"))).toBe(true);expect(checks.some(row=>row.id.startsWith("FORTUNE:"))).toBe(true);expect(checks.some(row=>row.id.startsWith("CATEGORY:"))).toBe(true);expect(checks.some(row=>row.id.startsWith("WELLNESS:"))).toBe(true);expect(checks.some(row=>row.id.startsWith("CHILD:"))).toBe(true);});
  it("keeps production results identical to trace outputs",()=>{const value=trace(),byId=new Map(value.steps.map(row=>[row.id,row.output])),fortune=analysis.fortune as FortuneResult;expect(byId.get("STRENGTH")).toEqual(analysis.strength);expect(byId.get("USEFUL_GOD_SYNTHESIS")).toEqual(analysis.usefulGods.synthesis);const tracedSynthesis=byId.get("FORTUNE_SYNTHESIS") as {daeun:Array<{favorability:unknown;activation:unknown;transformationAlignment:unknown}>};if(fortune.synthesis.status!=="implemented")throw new Error("fixture unavailable");expect(tracedSynthesis.daeun[0].favorability).toEqual(fortune.synthesis.daeun[0].favorability);expect(tracedSynthesis.daeun[0].activation).toEqual(fortune.synthesis.daeun[0].activation);expect(tracedSynthesis.daeun[0].transformationAlignment).toEqual(fortune.synthesis.daeun[0].transformationAlignment);const tracedCategories=byId.get("CATEGORY_FORTUNE") as {daeun:Array<{overallFlow:unknown}>};if(fortune.categories.status!=="implemented")throw new Error("fixture unavailable");expect(tracedCategories.daeun[0].overallFlow).toMatchObject({supportScore:fortune.categories.daeun[0].overallFlow.supportScore,activityScore:fortune.categories.daeun[0].overallFlow.activityScore});expect(byId.get("WELLNESS")).toEqual(analysis.wellness);expect(byId.get("CHILDREN_FORTUNE")).toEqual(analysis.childrenFortune);});
  it("keeps evidence IDs stable",()=>expect(trace().steps.map(row=>row.evidenceIds)).toEqual(trace().steps.map(row=>row.evidenceIds)));
  it("renders a local, collapsible HTML audit without external or customer UI dependencies",()=>{const html=renderCalibrationTraceHtml(trace());expect(html).toContain("<details open>");expect(html).toContain("입력 → 계산 → 결과");expect(html).toContain("재구성 통과");expect(html).not.toContain("<script");expect(html).not.toContain("OPENAI_API_KEY");});
  it("builds a non-ranking multi-case summary",()=>{const row=buildCalibrationSummary("SYNTHETIC-TRACE-001",analysis,[{domain:"PERSONALITY",classification:"UNKNOWN",mismatchTypes:[]}]);const summary=buildSummaryTable([row]);expect(summary.comparisonIsRanking).toBe(false);expect(row.dayMaster).toBe(analysis.dayMaster);expect(row.majorDaeun).toHaveLength(10);});
  it("keeps all private case roots ignored",async()=>{const ignore=await readFile(".gitignore","utf8");for(const path of ["calibration/private/**","benchmarks/private/**","fixtures/private/**"])expect(ignore).toContain(path);});
  it("supports anonymous assessments and non-authoritative external comparisons",()=>{const value=buildCalibrationTrace(analysis,{caseId:"CASE-001",assessments:[{domain:"WORK",classification:"PARTIAL",mismatchTypes:["COEFFICIENT_DIFFERENCE"],notes:"anonymous note"}],externalComparisons:[{service:"reference-service",notes:"학파 차이 검토",automaticErrorConclusion:false}]});expect(value.assessments[0].classification).toBe("PARTIAL");expect(value.externalComparisons[0].automaticErrorConclusion).toBe(false);});
});
