import { readFile } from "node:fs/promises";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { SajuInputForm } from "@/components/SajuInputForm";
import { calculateSaju } from "@/lib/saju/engine";
import { COUNTRY_OPTIONS, KR_CITY_OPTIONS, RELATIONSHIP_OPTIONS, datePickerParts, normalizeDateInput, normalizeTimeInput, timePickerParts, updateDatePickerPart, updateTimePickerPart } from "@/lib/saju/presentation/customer-input";
import { LIFETIME_REPORT_V2 } from "@/rules/lifetime-report.v2";
import { CUSTOMER_TERMINOLOGY_V1 } from "@/rules/customer-terminology.v1";
import { SYNTHETIC_INPUT } from "./synthetic-input";

const formSource = () => readFile("src/components/SajuInputForm.tsx", "utf8");
const selectSource = () => readFile("src/components/SearchSelect.tsx", "utf8");
const dateSource = () => readFile("src/components/HybridDateField.tsx", "utf8");
const timeSource = () => readFile("src/components/HybridTimeField.tsx", "utf8");
const reportSource = () => readFile("src/components/LifetimeReport.tsx", "utf8");

describe("CUSTOMER_LIFETIME_UI_V2 input", () => {
  it("offers exactly three relationship values", () => expect(RELATIONSHIP_OPTIONS).toEqual([{value:"SINGLE",label:"솔로"},{value:"DATING",label:"연애 중"},{value:"MARRIED",label:"기혼"}]));
  it("keeps relationship context out of deterministic input", () => { const stable=(value:ReturnType<typeof calculateSaju>)=>({...value,engineMetadata:{...value.engineMetadata,calculatedAt:"stable"}}),before=stable(calculateSaju(SYNTHETIC_INPUT)); for(const relationshipStatus of RELATIONSHIP_OPTIONS.map(row=>row.value)){ expect(stable(calculateSaju(SYNTHETIC_INPUT))).toEqual(before); expect(JSON.stringify(SYNTHETIC_INPUT)).not.toContain(relationshipStatus); } });
  it("uses a verified static country list and exposes KR", () => { expect(COUNTRY_OPTIONS.find(row=>row.value==="KR")?.label).toBe("대한민국"); expect(COUNTRY_OPTIONS.length).toBeGreaterThan(5); });
  it("supports Korean city search data and unknown city", () => { expect(KR_CITY_OPTIONS.filter(city=>city.includes("시흥"))).toEqual(["경기도 시흥시"]); expect(KR_CITY_OPTIONS).toContain("경기도 화성시"); expect(KR_CITY_OPTIONS).toContain("출생도시를 모름"); });
  it.each([["19950930","1995-09-30"],["1995-09-30","1995-09-30"],["1995-02-31",null],["1899-12-31",null],["2000-02-29","2000-02-29"],["1900-02-29",null]])("normalizes date %s",(input,expected)=>expect(normalizeDateInput(input)).toBe(expected));
  it("uses UTC date validation without a timezone date shift",()=>{expect(updateDatePickerPart("2024-02-29","year","2023")).toBe("2023-02-28");expect(updateDatePickerPart("1995-09-30","month","02")).toBe("1995-02-28");expect(datePickerParts("19950930")).toEqual({year:"1995",month:"09",day:"30"});});
  it.each([["0829","08:29"],["08:29","08:29"],["24:00",null],["09:60",null],["00:00","00:00"],["23:59","23:59"]])("normalizes time %s",(input,expected)=>expect(normalizeTimeInput(input)).toBe(expected));
  it("synchronizes picker values with canonical date and time",()=>{expect(datePickerParts(updateDatePickerPart("1995-09-30","day","12"))).toEqual({year:"1995",month:"09",day:"12"});expect(timePickerParts("0829")).toEqual({hour:"08",minute:"29"});expect(updateTimePickerPart("08:29","minute","47")).toBe("08:47");});
  it("renders exactly one editable date field and one editable time field",()=>{const html=renderToStaticMarkup(createElement(SajuInputForm,{onResult:()=>{}}));expect(html.match(/data-testid="birth-date-input"/g)).toHaveLength(1);expect(html.match(/data-testid="birth-time-input"/g)).toHaveLength(1);expect(html).not.toContain('type="date"');expect(html).not.toContain("직접 입력하기");expect(html).not.toContain("입력 모드");});
  it("provides all 24 hours and 60 minutes inside the one time picker", async()=>{const source=await timeSource();expect(source).toContain("length: 24");expect(source).toContain("length: 60");expect(source).toContain('placeholder="0829 또는 08:29"');expect(source).toContain('aria-label="출생 분"');});
  it("keeps date and time pickers anchored to their shared input field",async()=>{const date=await dateSource(),time=await timeSource();for(const source of [date,time]){expect(source).toContain('className="hybridInputShell"');expect(source).toContain('className="pickerMenu"');expect(source).toContain("getBoundingClientRect");expect(source).toContain("innerHeight - rect.bottom");expect(source).toContain("aria-expanded");}});
  it("names each picker in customer language when it flips above",async()=>{const date=await dateSource(),time=await timeSource(),css=await readFile("src/app/globals.css","utf8");expect(date).toContain("생년월일 선택</p>");expect(time).toContain("태어난 시각 선택</p>");expect(date).toContain("picker-title");expect(time).toContain("picker-title");expect(css).toContain(".pickerMenu::before");expect(css).toContain(".hybridPicker.opensAbove .pickerMenu::before");});
  it("keeps the requested customer input order",()=>{const html=renderToStaticMarkup(createElement(SajuInputForm,{onResult:()=>{}}));const labels=["이름","성별","현재 관계","생년월일","달력","태어난 시각","출생 국가","출생 도시"];const positions=labels.map(label=>html.indexOf(label));expect(positions.every(position=>position>=0)).toBe(true);expect(positions).toEqual([...positions].sort((a,b)=>a-b));});
  it("shows a lunar leap-month checkbox beside the calendar selector and still blocks unsupported lunar calculation",async()=>{const source=await formSource();expect(source).toContain('form.calendarType === "lunar"');expect(source).toContain('className="lunarLeapToggle"');expect(source).toContain('type="checkbox"');expect(source).toContain('checked={form.lunarLeapMonth==="leap"}');expect(source).toContain('event.target.checked ? "leap" : "normal"');expect(source).toContain("윤달인 경우 체크");expect(source).toContain("현재 음력→양력 변환 계산은 아직 준비 중입니다.");});
  it("blocks unsupported country and incomplete lunar mode", async()=>{const source=await formSource();expect(source).toContain("현재 해외 출생 계산은 지원되지 않습니다.");expect(source).toContain("음력 계산은 준비 중입니다.");});
  it("does not invent a time when it is unknown", async()=>{const source=await formSource();expect(source).toContain("임의 시간으로 계산하지 않습니다.");expect(source).toContain('birthTime: event.target.checked ? null : ""');});
  it("contains no child reality input", async()=>{const source=await formSource();for(const text of ["자녀 있음","몇 명","아들/딸","임신 여부","출산 계획"])expect(source).not.toContain(text);});
});

describe("CUSTOMER_LIFETIME_UI_V2 dropdown",()=>{
  it("uses an anchored absolute menu without layout growth",async()=>{const source=await selectSource(),css=await readFile("src/app/globals.css","utf8");expect(source).toContain('className="selectMenu"');expect(css).toContain(".selectMenu { position:absolute");expect(css).toContain("max-height:300px");});
  it("persists selected values and filters search",async()=>{const source=await selectSource();expect(source).toContain("option.value === value");expect(source).toContain("includes(query.trim().toLowerCase())");});
  it("supports keyboard and listbox semantics",async()=>{const source=await selectSource();for(const key of ["Escape","ArrowDown","ArrowUp","Home","End","Enter"])expect(source).toContain(key);expect(source).toContain('role="listbox"');expect(source).toContain('role="option"');expect(source).toContain("aria-selected");});
  it("flips above when lower viewport space is insufficient",async()=>expect(await selectSource()).toContain("innerHeight - rect.bottom < 340"));
});

describe("CUSTOMER_LIFETIME_UI_V2 report",()=>{
  it("shows each generation stage until every dynamic interpretation is ready",async()=>{const source=await reportSource(),page=await readFile("src/app/page.tsx","utf8");expect(source).toContain("사주책을 만들고 있어요");expect(source).toContain("중심 성향을 정리하고 있어요");expect(source).toContain("묶음을 한 권의 책으로 정리하고 있어요");expect(source).toContain("내용을 다 정리하면 한 번에 보여드릴게요");expect(source).toContain("해설이 완성되면 자동으로 결과가 열립니다.");expect(page).toContain('stage:"CHARACTER_CORE"');expect(page).toContain('stage:"PARTS"');expect(page).toContain('stage:"MERGE"');});
  it("keeps customer-facing generation copy free of internal English jargon",async()=>{const source=await reportSource(),preview=await readFile("src/app/dev/lifetime-report/page.tsx","utf8");expect(source).not.toContain("모든 section");expect(preview).not.toContain("이 section에서는");});
  it("keeps front matter and professional data out of the main reading flow",async()=>{const source=await reportSource();expect(source).toContain('const visibleSections=report.sections.filter(section=>section.contentKind==="CONTENT")');expect(source).toContain("visibleSections.map(section=>{const partNumber");expect(source).toContain("const sections=visibleSections.filter");expect(source).toContain("<ProfessionalChapter analysis={analysis} report={report}/>");});
  it("explains network failures and refresh recovery in Korean",async()=>{const form=await formSource(),page=await readFile("src/app/page.tsx","utf8");expect(form).toContain("네트워크 연결을 확인한 뒤 다시 시도해 주세요.");expect(page).toContain("새로고침되어 이전 결과를 다시 불러올 수 없어요.");expect(page).toContain("postpost-lifetime-result-active");});
  it("does not block the customer report on editorial length QA warnings",async()=>{const page=await readFile("src/app/page.tsx","utf8");expect(page).toContain('console.warn("lifetime_content_contract_warning"');expect(page).toContain("setInterpretation(merged)");});
  it("keeps the canonical 01~18 order",()=>expect(LIFETIME_REPORT_V2.sections.map(row=>row.chapterNumber)).toEqual(Array.from({length:18},(_,index)=>String(index+1).padStart(2,"0"))));
  it("uses centralized customer terminology",async()=>{const source=await reportSource();expect(source).toContain("customerElement");expect(source).toContain("customerTerm");expect(CUSTOMER_TERMINOLOGY_V1.terms.용신).toBe("나에게 가장 필요한 기운");});
  it("renders five representative element percentages",async()=>{const source=await reportSource();expect(source).toContain("adjusted?.[element].percentage");expect(source).toContain("ELEMENTS.map");});
  it("renders deterministic wellness with a plain medical disclaimer",async()=>{const source=await reportSource();expect(source).toContain("constitutionalBalanceScore");expect(source).toContain("병을 알아보는 검사가 아닙니다");});
  it("renders deterministic children without reality assumptions",async()=>{const source=await reportSource();expect(source).toContain("children.bond.score");expect(source).toContain("sonPercent");expect(source).toContain("daughterPercent");expect(source).not.toContain("현재 자녀와");expect(source).not.toContain("첫째");expect(source).not.toContain("둘째");});
  it("keeps support and activation separate",async()=>{const source=await reportSource();expect(source).toContain('label="도움받기 쉬운 정도"');expect(source).toContain('label="바빠지거나 바뀌는 정도"');expect(source).toContain("두 숫자를 합쳐 좋다거나 나쁘다고 말하지 않습니다");});
  it("keeps all ten daeun available in a controlled scroller",async()=>{const source=await reportSource();expect(source).toContain("periods.map");expect(source).toContain('className="daeunRail"');});
  it("keeps professional analysis collapsed without internal calculation mechanics",async()=>{const source=await reportSource();expect(source).toContain('id="chapter-18"');expect(source).not.toContain("버전과 evidence IDs");expect(source).not.toContain("rulesetVersion:analysis.rulesetVersion");expect(source).not.toContain("관계 반영 후");expect(source).not.toContain("태어난 순간 {pct");expect(source).toContain("내 사주 원국 한눈에 보기");});
  it("isolates AI failure while preserving deterministic chapters",async()=>{const source=await reportSource();expect(source).toContain('interpretation.status === "failed"');expect(source).toContain("계산된 평생사주 결과는 정상적으로 표시");});
  it("uses real text and no information image or canvas dependency",async()=>{const source=await reportSource();expect(source).not.toContain("<img");expect(source).not.toContain("<canvas");expect(source).toContain("삼족오 한마디");});
  it("ships deep, distinct Korean synthetic copy without repeated boilerplate",async()=>{const preview=await readFile("src/app/dev/lifetime-report/page.tsx","utf8");expect(preview).toContain("겉으로는");expect(preview).toContain("한 번에 큰돈");expect(preview).toContain("부모가 된다면");expect(preview).toContain("생활 습관");expect(preview.length).toBeGreaterThan(7000);expect(preview).not.toContain("이 장은 공개 합성 입력에서 계산된 근거만 사용합니다");expect(preview).not.toContain("OPENAI_API_KEY");});
  it("labels daeun with the actual calculated age range",async()=>{const source=await reportSource();expect(source).toContain("startAgeYears");expect(source).toContain("endAgeYears");expect(source).toContain("ordinalDaeun");expect(source).toContain(' 대운 · ');expect(source).toContain('className="periodIndicator"');});
  it("explains wellness percentages as element composition",async()=>{const source=await reportSource();expect(source).toContain("건강 점수가 아닙니다");expect(source).toContain("기운 <strong>");});
  it("places children metric explanations beside their values",async()=>{const source=await reportSource();expect(source).toContain("출산 가능성을 뜻하지 않습니다");expect(source).toContain("실제 아이의 성별을 맞히는 숫자가 아닙니다");});
  it("shows a reader-friendly four-pillar chart before chapter one",async()=>{const source=await reportSource();expect(source).toContain('className="sajuAtGlance"');expect(source).toContain('className="sajuPillarTable"');expect(source).toContain('position==="day"?"isDayPillar"');expect(source).toContain("나를 대표하는 일주");expect(source).toContain("pillarReading");expect(source).not.toContain("STEM_EASY");expect(source).not.toContain("BRANCH_ANIMAL");});
  it("does not repeat a part title as its first subsection heading",async()=>{const source=await reportSource();expect(source).toContain("duplicatePartOpening");expect(source).toContain("isPartOpening");});
  it("weaves the customer name into selected chapter openings without sending it to the interpretation provider",async()=>{const source=await reportSource();expect(source).toContain("PERSONAL_PART_LINES");expect(source).toContain("analysis.person.name");for(const part of ['"01":name=>','"03":name=>','"04":name=>','"05":name=>','"11":name=>','"13":name=>','"14":name=>'])expect(source).toContain(part);});
  it("explains the day pillar with personality words instead of only stem-branch meanings",async()=>{const source=await reportSource();expect(source).toContain("STEM_PERSONALITY");expect(source).toContain("BRANCH_PERSONALITY");expect(source).toContain('keywords.join(" · ")');expect(source).toContain("실제 성격에서 자주 보이는 모습");});
  it("shows the five-element spread once in the chapter-one snapshot",async()=>{const source=await reportSource();expect(source).toContain('className="fiveElementSpread"');expect(source).toContain("五行 · 오행 분포");expect(source).toContain("adjustedStrength.elements");expect(source).toContain('part.partNumber==="01"?<SajuAtGlance analysis={analysis}/>:null');expect(source).toContain("const showFiveElements=false");});
  it("uses familiar saju chapter names and the canonical section titles",async()=>{const source=await reportSource();expect(source).toContain('"01":"성격과 기본 성향"');expect(source).toContain('"03":"직업운·학업운"');expect(source).toContain('"04":"재물운"');expect(source).toContain('"13":"대운"');expect(source).toContain('const customerSectionTitle=(_id:string,fallback:string)=>fallback');});
  it("does not repeat generic evidence drawers on every dynamic page",async()=>{const source=await reportSource();expect(source).toContain('const showEvidence=Boolean(section.professionalDetails||section.metrics?.length)');expect(source).toContain("조금 더 깊이 보기");expect(source).not.toContain("왜 이렇게 보나요?");});
  it("formats customer labels Korean-first and professional labels Han-second",()=>{expect(CUSTOMER_TERMINOLOGY_V1.elements.wood).toEqual({customer:"나무",professional:"목(木)"});});
});
