import { LifetimePreviewClient } from "@/components/LifetimePreviewClient";
import { calculateSaju } from "@/lib/saju/engine";
import { selectCurrentPeriods } from "@/lib/saju/presentation/current-period";
import { LIFETIME_REPORT_V2 } from "@/rules/lifetime-report.v2";
import type { InterpretationUiState } from "@/types/customer-result";
import type { FortuneResult } from "@/types/fortune";
import type { SajuAnalysis } from "@/types/saju-analysis";

const fullAnalysis = calculateSaju({ name:"가상인물", gender:"female", calendarType:"solar", birthDate:"1995-09-30", birthTime:"08:29", birthTimeKnown:true, birthCountry:"KR", birthCityKnown:true, birthCity:"서울특별시" });
const fullFortune = fullAnalysis.fortune as FortuneResult;
// The preview renders Daeun and the first category summary only. Excluding unused
// Seun/Wolun arrays keeps this public synthetic route below platform ISR limits.
const analysis: SajuAnalysis = { ...fullAnalysis, fortune: { ...fullFortune,
  seun: fullFortune.seun.status === "implemented" ? { ...fullFortune.seun, periods: [], evidence: [] } : fullFortune.seun,
  wolun: fullFortune.wolun.status === "implemented" ? { ...fullFortune.wolun, periods: [], evidence: [] } : fullFortune.wolun,
  transformation: { status:"not_implemented" }, synthesis: { status:"not_implemented" },
  categories: fullFortune.categories.status === "implemented" ? { ...fullFortune.categories, seun:[], wolun:[], seunPeriodSummaries:[], wolunPeriodSummaries:[], evidence:[] } : fullFortune.categories,
} };
const previewCopy: Record<string, { headline:string; paragraphs:string[] }> = {
  overview:{headline:"기준을 세우고 긴 호흡으로 나만의 결과를 만드는 사람",paragraphs:["처음에는 주변을 충분히 살피지만, 기준이 선 뒤에는 쉽게 흔들리지 않습니다.","빠른 성취보다 시간이 지나도 남는 결과를 만들 때 만족감이 큽니다."]},
  personality:{headline:"차분히 살핀 뒤에는 자기 방식으로 끝까지 갑니다",paragraphs:["무엇을 결정할 때 분위기에 바로 휩쓸리기보다, 정보와 맥락을 충분히 모은 뒤 내 기준을 세우는 편입니다. 결론까지 시간이 걸려 보여도 한번 방향을 정하면 꾸준히 이어갑니다.","겉으로는 차분하고 유연해 보여도 속에는 분명한 선이 있습니다. 가까운 사람은 부드러움보다 단단한 고집을 먼저 느낄 때도 있습니다.","반복되는 행동 패턴은 ‘충분히 이해한 뒤 움직이기’입니다. 낯선 환경에서는 관찰자로 시작하고, 익숙해진 뒤에는 일의 순서와 기준을 정리하는 역할을 맡기 쉽습니다.","장점은 신중함과 지속력입니다. 작은 차이를 알아차리고, 한 번 시작한 일을 현실적인 결과로 연결하는 힘이 있습니다.","다만 장점이 과해지면 준비가 길어지고 이미 세운 기준을 바꾸기 어려워질 수 있습니다. 완벽한 확신보다 작은 시험을 먼저 해보는 방식이 균형을 돕습니다."]},
  "five-elements":{headline:"다섯 기운은 속도와 표현 방식을 서로 다르게 만듭니다",paragraphs:["쇠와 나무의 비중이 비교적 선명해, 기준을 세우는 힘과 성장하려는 힘이 함께 드러납니다.","물의 기운은 생각을 이어 주고 상황에 맞게 방향을 바꾸는 여유를 보탭니다.","불의 비중이 낮은 구성은 표현력이 없다는 뜻이 아닙니다. 마음속 결론을 바깥으로 빠르게 드러내는 일에 의식적인 준비가 필요하다는 의미에 가깝습니다.","다섯 비율은 우열표가 아니라 내가 어떤 방식에 익숙하고 어떤 방식을 의식적으로 꺼내 써야 하는지 보여주는 구성표입니다."]},
  strength:{headline:"혼자 밀어붙이기보다 좋은 환경을 연결할 때 힘이 납니다",paragraphs:["중심 힘은 균형에 가깝지만 주변 조건의 영향을 조금 더 섬세하게 받는 편입니다.","명확한 역할과 믿을 만한 사람이 있을 때 집중력이 안정되고, 혼자 모든 판단을 떠안을 때는 생각이 쉽게 많아질 수 있습니다.","도움을 받는 것은 약함이 아니라 자원을 정확히 연결하는 능력입니다. 시작 전에 필요한 정보와 협력 범위를 정하면 힘의 낭비가 줄어듭니다.","일정한 수면, 식사, 작업 순서처럼 예측 가능한 리듬이 중심을 오래 유지하는 데 도움을 줍니다."]},
  "strengths-and-cautions":{headline:"섬세함과 지속력은 강점이고, 과한 자기검열은 부담입니다",paragraphs:["작은 어긋남을 빠르게 발견하고 결과의 완성도를 높이는 데 강점이 있습니다.","급하게 앞서가기보다 필요한 순서를 세워 꾸준히 쌓는 방식이 신뢰로 이어집니다.","반대로 모든 조건이 갖춰져야 시작하려 하면 기회를 늦게 잡을 수 있습니다.","책임을 오래 붙들고 혼자 정리하려는 습관이 쌓이면 피로를 뒤늦게 알아차릴 수 있으니, 중간 점검과 역할 나누기가 중요합니다."]},
  "talent-and-work":{headline:"복잡한 것을 정리해 오래 쓸 수 있는 결과로 만드는 재능",paragraphs:["일할 때는 목표만 던져지는 것보다 이유와 기준을 이해할 때 실력이 빠르게 살아납니다. 흐트러진 정보에서 순서를 찾고, 반복 가능한 방식으로 정리하는 일에 강점이 있습니다.","조직에서는 역할과 책임이 분명할수록 안정적입니다. 동시에 세부 실행 방법에는 스스로 결정할 여지가 있어야 답답함이 줄어듭니다.","혼자 하는 일에서도 방향을 점검해 줄 동료나 고객의 피드백이 있으면 완성도가 높아집니다. 완전한 독립보다 기준 있는 자율에 가깝습니다.","설명 없이 자주 바뀌는 지시, 속도만 강조하는 환경, 결과보다 보여주기를 앞세우는 분위기에서는 에너지가 빠르게 소모될 수 있습니다.","재능을 잘 쓰려면 분석과 정리를 실제 산출물로 끝내는 마감 장치를 두세요. 기록, 편집, 기획, 운영처럼 생각을 구조로 바꾸는 역할이 잘 맞습니다."]},
  "money-style":{headline:"돈은 크게 흔들기보다 기준을 세워 오래 관리하는 편",paragraphs:["돈을 버는 방식에서는 한 번의 큰 승부보다 실력과 신뢰가 반복 수입으로 이어지는 구조가 편안합니다. 내가 이해할 수 있는 일에서 현실적인 성과를 쌓을 때 안정감이 생깁니다.","관리할 때는 목적이 분명한 지출에는 과감하지만, 기준 없는 소비에는 신중합니다. 숫자를 자주 확인하기보다 용도별 경계를 정해 두는 방식이 잘 맞습니다.","확장과 안정 사이에서는 기본적으로 안전판을 먼저 찾습니다. 다만 확신이 생긴 뒤에는 예상보다 범위를 크게 넓힐 수 있어, 결정 전 한도를 정하는 것이 중요합니다.","반복하기 쉬운 습관은 오래 고민한 뒤 한 번에 지출하거나, 책임감을 이유로 다른 사람의 몫까지 떠안는 것입니다.","강점은 축적과 관리이고 주의점은 늦어진 판단입니다. 작은 규모로 먼저 시험하고 결과를 기록하면 안정성을 지키면서 기회를 놓치지 않을 수 있습니다."]},
  relationship:{headline:"솔로인 지금, 호감보다 오래 맞는 기준을 먼저 봅니다",paragraphs:["새로운 만남에서는 빠른 설렘보다 대화의 결, 약속을 지키는 태도, 생활 리듬이 맞는지를 천천히 확인하는 편입니다.","처음에는 감정을 크게 드러내지 않아 상대가 거리감을 느낄 수 있지만, 신뢰가 쌓이면 행동으로 꾸준히 마음을 보여 줍니다.","사람을 고를 때는 말의 화려함보다 일관성을 중요하게 봅니다. 서로의 독립성을 존중하면서 필요한 순간에는 분명히 연결되는 관계가 편안합니다.","갈등에서는 바로 부딪치기보다 생각을 정리한 뒤 말하려는 경향이 있습니다. 침묵이 길어지기 전에 ‘지금 필요한 시간’을 설명하면 오해를 줄일 수 있습니다.","새로운 관계를 위해 기준을 낮출 필요는 없습니다. 다만 상대가 알아서 이해하기를 기다리기보다 내 기대와 속도를 말로 알려 주는 연습이 도움이 됩니다."]},
  children:{headline:"아이와의 관계에서는 안정된 기준과 세심한 관찰이 강점입니다",paragraphs:["자녀 관계 영역은 넓게 퍼지기보다 선택적으로 드러나는 편입니다. 숫자가 낮다고 인연의 좋고 나쁨이나 출산 가능성을 뜻하지는 않습니다.","자녀 수 경향 역시 실제 인원 예측이 아니라 관계 에너지가 한두 방향에 집중되는지, 여러 방향으로 확장되는지를 보는 전통적 표현입니다.","아들 쪽과 딸 쪽 비율은 태아 성별 확률이 아닙니다. 서로 다른 상징 기운이 현재 원국에서 차지하는 상대적 크기만 비교합니다.","부모 역할에서는 규칙을 세우고 생활을 안정시키는 힘이 먼저 나타납니다. 아이의 작은 변화를 알아차리고 필요한 것을 미리 준비하는 데 강점이 있습니다.","관계의 강점은 꾸준함과 책임감입니다. 말보다 행동으로 신뢰를 쌓고, 한번 맡은 역할을 오래 유지합니다.","주의할 점은 보호와 기대가 지나치게 촘촘해지는 순간입니다. 아이의 속도와 선택 여지를 남기는 것이 관계의 숨통을 넓혀 줍니다."]},
  wellness:{headline:"컨디션은 긴장과 회복의 리듬을 일정하게 만들 때 안정됩니다",paragraphs:["오행 구성에서는 쇠·나무·물의 흐름이 상대적으로 선명하고 불의 비중은 낮습니다. 이는 질병 진단이 아니라 생활 리듬을 읽기 위한 체질적 구조입니다.","기준을 세우고 집중하는 힘은 비교적 잘 드러납니다. 계획이 정리된 날에는 몸과 마음의 리듬도 함께 안정되기 쉽습니다.","보완이 필요한 부분은 활력의 점화와 긴장 뒤 회복입니다. 오래 앉아 생각만 이어가기보다 짧은 움직임과 햇빛, 일정한 식사 시간을 활용하는 편이 좋습니다.","일이 몰릴수록 휴식을 나중으로 미루기 쉽습니다. 피로가 크게 느껴진 뒤 쉬는 방식보다, 하루 안에 짧은 회복 구간을 미리 넣는 방식이 맞습니다.","활동은 한꺼번에 강도를 높이기보다 자주 반복하는 편이 안정적입니다. 휴식도 아무것도 하지 않는 시간과 감각을 바꾸는 가벼운 활동을 나누어 보세요.","평생 흐름에서는 변화가 큰 구간에 컨디션 기복도 커질 수 있습니다. 일정과 역할이 바뀔 때 수면·식사·움직임 세 가지를 먼저 고정하는 것이 도움이 됩니다."]},
  "helpful-elements":{headline:"물·나무·불의 성질을 상황에 맞게 꺼내 쓰세요",paragraphs:["물의 유연함은 생각을 연결하고 막힌 상황에서 다른 길을 찾게 돕습니다.","나무의 성장성은 배운 것을 실제 행동으로 이어 주고, 불의 표현력은 준비한 내용을 바깥에 알리는 힘을 보탭니다.","도움 흐름은 성공 확률이 아니라 현재 원국의 균형을 보완하는 상대적 방향입니다."]},
  "special-features":{headline:"배움과 표현을 깊게 파고드는 특징이 눈에 띕니다",paragraphs:["관심이 생긴 주제는 표면만 훑기보다 원리와 맥락까지 알고 싶어 하는 면이 있습니다.","혼자 생각을 정리하는 시간이 창작과 전문성으로 이어지기 쉽습니다.","전통 별과 신살은 이런 특징을 보조해서 읽는 이름이며, 사건의 길흉을 단독으로 결정하지 않습니다."]},
  "inner-roles":{headline:"책임지는 나, 배우는 나, 표현하는 내가 번갈아 앞에 섭니다",paragraphs:["기준이 필요한 자리에서는 책임을 맡고 질서를 만드는 모습이 먼저 나옵니다.","새로운 정보를 만날 때는 충분히 관찰하고 내 언어로 다시 정리합니다.","안전하다고 느끼는 관계에서는 평소보다 솔직하고 장난스러운 표현도 자연스럽게 드러납니다.","한 모습만 진짜라고 고르기보다 상황마다 어떤 역할에 힘이 실리는지 아는 것이 중요합니다."]},
  "lifetime-flow":{headline:"평생의 흐름은 준비와 확장이 교대로 이어집니다",paragraphs:["초반에는 경험을 모으고 기준을 만드는 시간이 중요합니다.","중반으로 갈수록 쌓은 전문성을 바깥의 역할과 성과로 연결하는 질문이 커집니다.","후반에는 직접 해내는 일뿐 아니라 축적한 기준을 전하고 관계를 정돈하는 힘이 중요해집니다.","각 시기는 고정된 사건이 아니라 어떤 선택이 자연스럽게 느껴지는지 보여 주는 배경입니다."]},
  daeun:{headline:"열 개의 큰 구간마다 도움의 방향과 변화의 크기가 달라집니다",paragraphs:["앞선 구간에서 만든 기반은 다음 구간의 선택 재료가 됩니다. 한 시기만 떼어 좋고 나쁨으로 판단하기보다 이어지는 방향을 함께 보세요.","도움 흐름이 높을 때는 자원을 연결하기 쉽고, 변화 움직임이 높을 때는 역할과 환경이 활발하게 바뀔 수 있습니다.","도움이 많아도 변화는 잔잔할 수 있고, 변화가 커도 반드시 부담스러운 것은 아닙니다.","현재 선택한 구간의 한글 간지와 기간을 먼저 읽고, 전문 한자는 보조 정보로 확인하세요."]},
  "life-phases":{headline:"초반에는 기반, 중반에는 선택, 후반에는 전수가 중심이 됩니다",paragraphs:["인생 초반에는 다양한 경험을 통해 내 기준을 만드는 일이 중요합니다.","중반에는 무엇을 계속하고 무엇을 내려놓을지 선택하는 힘이 커집니다.","후반에는 축적한 지식과 관계를 정리해 다른 사람과 나누는 방식이 의미를 만듭니다."]},
  takeaways:{headline:"꾸준함을 지키되, 확신을 기다리느라 시작을 늦추지 마세요",paragraphs:["당신의 힘은 빠른 반응보다 오래 유지되는 기준에서 나옵니다.","주변의 도움을 정확히 연결하는 것은 의존이 아니라 중요한 역량입니다.","완벽한 준비보다 작은 실행을 먼저 두면 신중함이 기회로 이어집니다.","변화가 큰 때에는 속도를 높이기보다 생활 리듬과 우선순위를 먼저 고정하세요."]},
  professional:{headline:"쉬운 해석 뒤에는 같은 계산 근거가 놓여 있습니다",paragraphs:["이곳에서는 앞 장에서 사용한 원국, 오행 분포, 강약, 구조와 도움 기운을 전문 명칭과 함께 확인할 수 있습니다.","전문용어는 새로운 판단을 추가하는 것이 아니라 이미 본 고객용 설명의 계산 출처를 보여 줍니다."]},
};
const interpretation: InterpretationUiState = { status:"completed", ruleVersion:"ai-interpretation-v1", promptVersion:"interpretation-prompt-v1", groundingVersion:"interpretation-grounding-v1", analysisHash:"synthetic-preview", cacheKey:"synthetic-preview", metadata:{provider:"synthetic",model:"layout-preview",repaired:false}, report:{ status:"completed",reportType:"LIFETIME_GENERAL",headline:"기준을 세우고 긴 호흡으로 나만의 결과를 만드는 사람",summary:"서두르기보다 충분히 살피고, 한번 정한 방향은 꾸준히 이어가는 힘이 돋보입니다.",sections:LIFETIME_REPORT_V2.sections.map(section=>{const copy=previewCopy[section.id];return {id:section.id,chapterNumber:section.chapterNumber,title:section.title,headline:copy.headline,lead:"타고난 구성과 평생의 흐름을 생활 속 언어로 읽어봅니다.",body:copy.paragraphs.join("\n\n"),paragraphs:copy.paragraphs,keyPoints:[copy.paragraphs[0]],evidenceIds:["SYNTHETIC:EVIDENCE"],mascotComment:"내 속도와 리듬을 기억하세요."};}),highlights:["기준을 세우고 꾸준히 이어가는 힘이 있습니다."],cautions:["강한 책임감이 부담으로 쌓이지 않도록 회복 시간을 챙기세요."],timeline:[],disclaimer:"전통 명리의 경향 해석이며 확정적 사건 예측이 아닙니다." } };

export default function LifetimePreview() { return <LifetimePreviewClient analysis={analysis} current={selectCurrentPeriods(analysis)} interpretation={interpretation} />; }
