import { CHILDREN_FORTUNE_V1 as RULE } from "@/rules/children-fortune.v1";
import { tenGodCategory,categoryElement } from "../interpretation/ten-god-category";
import type { Element,FiveElementsResult,PillarPosition,RelationsResult,TenGodsValue,TwelveStagesValue } from "@/types/saju-analysis";
import type { FortuneResult } from "@/types/fortune";
import type { SynthesisResult } from "@/types/useful-gods";
import type { ChildActivationLevel,ChildBondLevel,ChildContribution,ChildCountBand,ChildrenFortuneResult } from "@/types/children-fortune";
import type { TenGodCategory } from "@/rules/structure-useful-god.v1";

const clamp=(value:number)=>Math.max(0,Math.min(100,value));
const positions:PillarPosition[]=["year","month","day","hour"];
const contribution=(evidenceId:string,factor:string,value:number,weight:number):ChildContribution=>({evidenceId,factor,value,weight,contribution:value*weight});
export const childBondLevel=(score:number):ChildBondLevel=>score>=RULE.bondThresholds.veryStrong?"VERY_STRONG":score>=RULE.bondThresholds.strong?"STRONG":score>=RULE.bondThresholds.moderate?"MODERATE":"LOW";
export const childCountBand=(score:number):ChildCountBand=>score>=RULE.countThresholds.multiple?"MULTIPLE_TENDENCY":score>=RULE.countThresholds.oneToTwo?"ONE_TO_TWO":score>=RULE.countThresholds.oneCentered?"ONE_CHILD_CENTERED":"LOW_CONNECTION";
export const childActivationLevel=(score:number):ChildActivationLevel=>score>=RULE.activationThresholds.veryHigh?"VERY_HIGH":score>=RULE.activationThresholds.high?"HIGH":score>=RULE.activationThresholds.moderate?"MODERATE":"LOW";
export function classifyGenderEnergy(sonScore:number,daughterScore:number){const total=sonScore+daughterScore,sonPercent=total?sonScore/total*100:50,daughterPercent=100-sonPercent,margin=Math.abs(sonPercent-daughterPercent),dominant=margin<RULE.balancedGenderMargin?"BALANCED" as const:sonPercent>daughterPercent?"SON" as const:"DAUGHTER" as const;return{sonPercent,daughterPercent,margin,dominant};}
const score=(rows:ChildContribution[])=>clamp(rows.reduce((sum,row)=>sum+row.contribution,0));
const relationRows=(relations:RelationsResult)=>[...Object.values(relations.heavenlyStems).flat(),...Object.values(relations.earthlyBranches).flat()];

function hourProfile(tenGods:TenGodsValue){const profile={companion:0,resource:0,output:0,wealth:0,officer:0} satisfies Record<TenGodCategory,number>;
  profile[tenGodCategory(tenGods.heavenlyStems.hour.korean)]+=40;const hidden=tenGods.hiddenStems.hour,
    raw=hidden.map(row=>RULE.hiddenWeights[row.role]),total=raw.reduce((a,b)=>a+b,0);
  hidden.forEach((row,index)=>profile[tenGodCategory(row.tenGod.korean)]+=60*raw[index]/total);return profile;}
export function classifyParenting(profile:Record<TenGodCategory,number>):ChildrenFortuneResult["parentingStyle"]{
  const clear=(a:number,b:number)=>a>=RULE.parenting.minimumClearScore&&a-b>RULE.parenting.mixedMargin;
  const expression=clear(profile.output,profile.resource)?"EXPRESSIVE":clear(profile.resource,profile.output)?"RESERVED":Math.abs(profile.output-profile.resource)<=RULE.parenting.mixedMargin?"MIXED":"PRACTICAL";
  const guidance=profile.officer>=RULE.parenting.minimumClearScore?"STRUCTURED":profile.output>=RULE.parenting.minimumClearScore?"AUTONOMY_ORIENTED":profile.resource>=RULE.parenting.minimumClearScore?"PROTECTIVE":"BALANCED";
  const expectation=profile.officer>=RULE.parenting.minimumClearScore?"HIGH_EXPECTATION":profile.companion>=RULE.parenting.minimumClearScore?"FLEXIBLE":profile.resource+profile.output>=RULE.parenting.supportiveCombinedMinimum?"SUPPORTIVE":"MIXED";
  const conflict=profile.output>=RULE.parenting.minimumClearScore?"DIRECT":profile.resource>=RULE.parenting.minimumClearScore?"INTERNALIZE":profile.officer>=RULE.parenting.minimumClearScore?"NEGOTIATE":profile.companion>=RULE.parenting.minimumClearScore?"DISTANCE":"NEGOTIATE";
  return{expression,guidance,expectation,conflict,sourceProfile:{...profile},evidenceIds:["CHILD-PARENTING-HOUR-STEM","CHILD-PARENTING-HOUR-HIDDEN"]};}

export function evaluateChildrenFortune(input:{dayMaster:Parameters<typeof categoryElement>[0];tenGods:TenGodsValue;twelveStages:TwelveStagesValue;
  fiveElements:FiveElementsResult;relations:RelationsResult;useful:SynthesisResult;fortune:FortuneResult}):ChildrenFortuneResult{
  if(!input.fiveElements.adjustedStrength.elements||!input.fiveElements.nativeStrength||input.fortune.daeun.status!=="implemented"||input.fortune.synthesis.status!=="implemented"||input.fortune.transformation.status!=="implemented")throw new Error("Complete deterministic child-fortune sources required");
  const outputElement:Element=categoryElement(input.dayMaster,"output"),adjustedPct=input.fiveElements.adjustedStrength.elements[outputElement].percentage,nativePct=input.fiveElements.nativeStrength[outputElement].percentage,
    nativePresence=clamp(nativePct/RULE.outputPresenceSaturationPercent*100),adjustedPresence=clamp(adjustedPct/RULE.outputPresenceSaturationPercent*100),outputPresence=nativePresence*RULE.outputPresenceWeights.native+adjustedPresence*RULE.outputPresenceWeights.adjusted,
    outputSources=input.fiveElements.evidence.filter(row=>row.originalElement===outputElement),outputNativeTotal=outputSources.reduce((sum,row)=>sum+row.nativeContribution,0),outputHiddenTotal=outputSources.filter(row=>row.sourceType==="HIDDEN_STEM").reduce((sum,row)=>sum+row.nativeContribution,0),outputRootAvailability=outputNativeTotal?outputHiddenTotal/outputNativeTotal*100:0,
    hour=hourProfile(input.tenGods),hourOutput=hour.output,
    stage=input.twelveStages.stages.hour.korean,stageSalience=RULE.stageSalience[stage]??50,useful=input.useful.elements.find(row=>row.element===outputElement)?.score??50,
    hourRelations=relationRows(input.relations).filter(row=>row.positions.includes("hour")),relationSalience=clamp(hourRelations.length*RULE.relationSaliencePerRelation);
  const bondContributions=[contribution("CHILD-OUTPUT-COMBINED","OUTPUT_PRESENCE",outputPresence,RULE.bondWeights.outputPresence),contribution("CHILD-OUTPUT-ROOT","OUTPUT_ROOT_AVAILABILITY",outputRootAvailability,RULE.bondWeights.outputRootAvailability),contribution("CHILD-HOUR-OUTPUT","HOUR_OUTPUT",hourOutput,RULE.bondWeights.hourOutput),
    contribution("CHILD-HOUR-STAGE","HOUR_TWELVE_STAGE",stageSalience,RULE.bondWeights.hourStage),contribution("CHILD-OUTPUT-USEFUL","OUTPUT_ELEMENT_ALIGNMENT",useful,RULE.bondWeights.usefulAlignment),contribution("CHILD-HOUR-RELATIONS","HOUR_RELATION_SALIENCE",relationSalience,RULE.bondWeights.relationSalience)],bondScore=score(bondContributions);
  const countContributions=[contribution("CHILD-COUNT-OUTPUT","OUTPUT_PRESENCE",outputPresence,RULE.countWeights.outputPresence),contribution("CHILD-COUNT-ROOT","OUTPUT_ROOT_AVAILABILITY",outputRootAvailability,RULE.countWeights.outputRootAvailability),contribution("CHILD-COUNT-HOUR","HOUR_OUTPUT",hourOutput,RULE.countWeights.hourOutput),contribution("CHILD-COUNT-STAGE","HOUR_TWELVE_STAGE",stageSalience,RULE.countWeights.hourStage)],countScore=score(countContributions),countBand=childCountBand(countScore);
  let sonSignal=0,daughterSignal=0,differentiated=0;for(const position of positions){if(position!=="day"){const god=input.tenGods.heavenlyStems[position].korean;if(god==="식신"||god==="상관"){const value=RULE.visibleOutputWeight+(position==="hour"?RULE.hourVisibleBonus:0);if(god==="식신")sonSignal+=value;else daughterSignal+=value;differentiated++;}}
    for(const row of input.tenGods.hiddenStems[position])if(row.tenGod.korean==="식신"||row.tenGod.korean==="상관"){const value=RULE.hiddenWeights[row.role]*(position==="hour"?RULE.hourPositionMultiplier:1)*10;if(row.tenGod.korean==="식신")sonSignal+=value;else daughterSignal+=value;differentiated+=RULE.hiddenWeights[row.role];}}
  const shared=adjustedPct/2,sonScore=shared+sonSignal,daughterScore=shared+daughterSignal,{sonPercent,daughterPercent,margin,dominant}=classifyGenderEnergy(sonScore,daughterScore),genderConfidence=differentiated>=RULE.genderConfidence.high?"HIGH":differentiated>=RULE.genderConfidence.medium?"MEDIUM":"LOW",
    genderScoreEvidence=[{evidenceId:"CHILD-GENDER-SHARED-OUTPUT-SON",target:"SON" as const,value:shared},{evidenceId:"CHILD-GENDER-SIKSIN-SON-SYMBOL",target:"SON" as const,value:sonSignal},{evidenceId:"CHILD-GENDER-SHARED-OUTPUT-DAUGHTER",target:"DAUGHTER" as const,value:shared},{evidenceId:"CHILD-GENDER-SANGGWAN-DAUGHTER-SYMBOL",target:"DAUGHTER" as const,value:daughterSignal}];
  const parentingStyle=classifyParenting(hour),strengthMap={EXPRESSIVE:"대화를 이끌어가는 힘",PRACTICAL:"현실적으로 도와주는 힘",RESERVED:"성장 과정을 오래 지켜보는 힘",MIXED:"말과 행동을 함께 조절하는 힘",STRUCTURED:"기준을 만들어주는 힘",AUTONOMY_ORIENTED:"자율성을 존중하는 힘",PROTECTIVE:"필요한 때 보호해주는 힘",BALANCED:"상황에 맞춰 거리를 조절하는 힘"} as const,
    attentionMap={HIGH_EXPECTATION:"기대치가 너무 높아지지 않도록 살피기",FLEXIBLE:"기준이 자주 달라지지 않도록 살피기",SUPPORTIVE:"걱정 때문에 먼저 개입하지 않도록 살피기",MIXED:"아이보다 먼저 결론 내리지 않도록 살피기",DIRECT:"말이 앞서 결론처럼 들리지 않도록 살피기",INTERNALIZE:"마음을 행동으로만 보여주지 않도록 살피기",NEGOTIATE:"설명이 길어져 압박이 되지 않도록 살피기",DISTANCE:"갈등 때 거리를 너무 오래 두지 않도록 살피기"} as const;
  const synthesis=input.fortune.synthesis,transformation=input.fortune.transformation,daeunPeriods=input.fortune.daeun.periods.map(period=>{const synthesisRow=synthesis.daeun.find(row=>row.context.daeunIndex===period.index),snapshot=transformation.daeunSnapshots.find(row=>row.context.daeunIndex===period.index),profile=snapshot?.layerProfiles.find(row=>row.layer==="DAEUN"),relevantElementShare=profile?.percentages[outputElement]??0,
      hourRelationActivation=clamp(period.interactions.filter(row=>row.natalPosition==="hour").reduce((sum,row)=>sum+row.activationPoints,0)),outputFlow=synthesisRow?.tenGodFlow.output??0,
      contributions=[contribution(`CHILD-PERIOD-${period.index}-ACTIVATION`,"EXISTING_ACTIVATION",period.activation.score,RULE.periodWeights.existingActivation),contribution(`CHILD-PERIOD-${period.index}-OUTPUT`,"OUTPUT_FLOW",outputFlow,RULE.periodWeights.outputFlow),contribution(`CHILD-PERIOD-${period.index}-HOUR`,"HOUR_RELATION_ACTIVATION",hourRelationActivation,RULE.periodWeights.hourRelationActivation),contribution(`CHILD-PERIOD-${period.index}-ELEMENT`,"RELEVANT_ELEMENT_SHARE",relevantElementShare,RULE.periodWeights.relevantElementShare)],activationScore=score(contributions),themes=[...(outputFlow>=RULE.periodThemeThresholds.highOutputFlow?["표현·성장 역할 활성"]:[]),...(hourRelationActivation>0?["자녀 영역과의 관계 변화"]:[]),...(period.activation.score>=RULE.periodThemeThresholds.highActivation?["생활 변화가 큰 흐름"]:[])];
    return{periodIndex:period.index,ageRange:period.sourcePeriod.ageRange,pillar:`${period.pillar.stem}${period.pillar.branch}`,activationScore,activationLevel:childActivationLevel(activationScore),themes:themes.length?themes:["가족 역할의 안정적 흐름"],contributions,evidenceIds:contributions.map(row=>row.evidenceId)};});
  return{status:"implemented",versions:{childrenFortune:RULE.ruleVersion,bond:RULE.bondVersion,countTendency:RULE.countTendencyVersion,genderEnergy:RULE.genderEnergyVersion,parentingStyle:RULE.parentingStyleVersion,periodActivation:RULE.periodActivationVersion},
    bond:{score:bondScore,level:childBondLevel(bondScore),contributions:bondContributions,evidenceIds:bondContributions.map(row=>row.evidenceId)},countTendency:{band:countBand,label:RULE.countLabels[countBand],score:countScore,confidence:hourOutput>=RULE.countConfidence.highHourOutput?"HIGH":adjustedPct>RULE.countConfidence.minimumAdjustedPresence?"MEDIUM":"LOW",contributions:countContributions,evidenceIds:countContributions.map(row=>row.evidenceId)},
    genderEnergy:{sonScore,daughterScore,sonPercent,daughterPercent,dominant,margin,confidence:genderConfidence,scoreEvidence:genderScoreEvidence,evidenceIds:[...genderScoreEvidence.map(row=>row.evidenceId),"CHILD-GENDER-NOT-BIOLOGICAL-PROBABILITY"]},parentingStyle,
    strengths:[{text:strengthMap[parentingStyle.expression],evidenceIds:parentingStyle.evidenceIds},{text:strengthMap[parentingStyle.guidance],evidenceIds:parentingStyle.evidenceIds}],attentionAreas:[{text:attentionMap[parentingStyle.expectation],evidenceIds:parentingStyle.evidenceIds},{text:attentionMap[parentingStyle.conflict],evidenceIds:parentingStyle.evidenceIds}],daeunPeriods,
    evidence:[`CHILD-OUTPUT-ELEMENT:${outputElement}`,`CHILD-OUTPUT-NATIVE-PCT:${nativePct}`,`CHILD-OUTPUT-ADJUSTED-PCT:${adjustedPct}`,`CHILD-OUTPUT-HIDDEN-AVAILABILITY:${outputRootAvailability}`,`CHILD-HOUR-STAGE:${stage}`,`CHILD-HOUR-RELATION-COUNT:${hourRelations.length}`,...hourRelations.map(row=>`CHILD-HOUR-RELATION:${row.id}:context-only`),"합충형파해는 좋고 나쁨이 아니라 연결·긴장·변화 context","성별 기운은 POSTPOST custom traditional symbolism이며 실제 출생 성별 확률이 아님"],disclaimer:{tendencyOnly:true,pregnancyProbability:false,exactChildCount:false,fetalSexPrediction:false}};}
