"use client";
import { FormEvent, useEffect, useState } from "react";
import { HybridDateField } from "@/components/HybridDateField";
import { HybridTimeField } from "@/components/HybridTimeField";
import { SearchSelect } from "@/components/SearchSelect";
import { COUNTRY_OPTIONS,KR_CITY_OPTIONS,RELATIONSHIP_OPTIONS,normalizeDateInput,normalizeTimeInput } from "@/lib/saju/presentation/customer-input";
import type { LocalCalibrationInput,CalibrationCaseListItem } from "@/types/local-calibration";
import type { AuditClassification,AuditDomain,MismatchType } from "@/types/calibration-trace";

const cityOptions=KR_CITY_OPTIONS.map(label=>({value:label==="출생도시를 모름"?"UNKNOWN":label,label}));
const initial:LocalCalibrationInput={name:"",gender:"female",calendarType:"solar",birthDate:"",birthTime:"",birthTimeKnown:true,birthCountry:"KR",birthCityKnown:true,birthCity:"",relationshipStatus:"SINGLE",preNotes:""};
const domains:AuditDomain[]=["PERSONALITY","WORK","MONEY","RELATIONSHIP","HEALTH_LIFESTYLE","FAMILY_CHILDREN","MAJOR_LIFE_CHANGES"];
const mismatchTypes:MismatchType[]=["FACT_ERROR","SCHOOL_DIFFERENCE","COEFFICIENT_DIFFERENCE","INTERPRETATION_DIFFERENCE","USER_EXPERIENCE_MISMATCH","TRACE_ERROR"];
const elementNames:Record<string,string>={wood:"나무",fire:"불",earth:"흙",metal:"쇠",water:"물"};
const pretty=(value:unknown)=><pre>{JSON.stringify(value,null,2)}</pre>;

export function CalibrationClient(){
 const [cases,setCases]=useState<CalibrationCaseListItem[]>([]),[selected,setSelected]=useState<string>(),[form,setForm]=useState(initial),[view,setView]=useState<any>(),[audit,setAudit]=useState<any>(),[error,setError]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("CORE");
 const refresh=async()=>{const r=await fetch("/api/dev/calibration/cases");if(r.ok)setCases((await r.json()).cases);};useEffect(()=>{refresh();},[]);
 const update=<K extends keyof LocalCalibrationInput>(key:K,value:LocalCalibrationInput[K])=>setForm(current=>({...current,[key]:value}));
 async function submit(event:FormEvent){event.preventDefault();setError("");const date=normalizeDateInput(form.birthDate),time=normalizeTimeInput(form.birthTime??"");if(!date||!time||form.calendarType!=="solar"||form.birthCountry!=="KR"||(form.birthCityKnown&&!form.birthCity)){setError("날짜·시각·달력·출생지를 확인해 주세요.");return;}setBusy(true);try{const created=await fetch("/api/dev/calibration/cases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,birthDate:date,birthTime:time})}).then(r=>r.json());setSelected(created.caseId);const analyzed=await fetch(`/api/dev/calibration/cases/${created.caseId}/analyze`,{method:"POST"});const body=await analyzed.json();setView(body);setAudit(created.audit);setTab("FACT");await refresh();}finally{setBusy(false);}}
 async function openCase(caseId:string){const r=await fetch(`/api/dev/calibration/cases/${caseId}`),body=await r.json();setSelected(caseId);setForm(body.input);setAudit(body.audit);setView(undefined);setTab("CORE");}
 async function analyze(){if(!selected)return;setBusy(true);const r=await fetch(`/api/dev/calibration/cases/${selected}/analyze`,{method:"POST"});setView(await r.json());setTab("FACT");setBusy(false);await refresh();}
 async function saveInput(){if(!selected)return;const response=await fetch(`/api/dev/calibration/cases/${selected}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({input:form})}),body=await response.json();setAudit(body.audit);await refresh();}
 async function saveAudit(next:any){if(!selected)return;setAudit(next);await fetch(`/api/dev/calibration/cases/${selected}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({audit:next})});await refresh();}
 async function remove(){if(!selected||!confirm(`${selected}의 비공개 파일을 모두 삭제할까요?`))return;await fetch(`/api/dev/calibration/cases/${selected}?confirm=${selected}`,{method:"DELETE"});setSelected(undefined);setView(undefined);setForm(initial);await refresh();}
 return <main className="calibrationApp"><aside className="caseRail"><header><small>LOCAL ONLY · PRIVATE</small><h1>Calibration</h1><p>사례를 비교하기 전에 계산 근거부터 확인합니다.</p></header><button className="newCase" onClick={()=>{setSelected(undefined);setView(undefined);setForm(initial);}}>+ 새 CASE</button><nav aria-label="비공개 사례 목록">{cases.map(item=><button key={item.caseId} className={selected===item.caseId?"active":""} onClick={()=>openCase(item.caseId)}><b>{item.caseId}</b><span>{item.status}{item.stale?" · 재분석 필요":""}</span></button>)}</nav><button className="summaryLink" onClick={()=>setTab("SUMMARY")}>다중 사례 요약</button></aside>
 <section className="calibrationMain">{!selected&&<NewCaseForm form={form} update={update} submit={submit} error={error} busy={busy}/>} {selected&&<><header className="caseHeader"><div><small>PRIVATE CASE</small><h2>{selected}</h2><p>{audit?.stale?"입력이 변경되어 재분석이 필요합니다.":"production engine과 동일한 결과를 사용합니다."}</p></div><div><button onClick={()=>setTab("INPUT")}>입력 수정</button><button onClick={analyze} disabled={busy}>{busy?"분석 중…":"다시 분석"}</button><button className="danger" onClick={remove}>삭제</button></div></header><nav className="auditTabs">{["FACT","CORE","FORTUNE","DOMAIN","SELF REPORT","TRACE","SUMMARY"].map(name=><button className={tab===name?"active":""} key={name} onClick={()=>setTab(name)}>{name}</button>)}</nav>{tab==="INPUT"&&<CaseEditForm form={form} update={update} save={saveInput}/>} {!view&&!["INPUT","SELF REPORT","SUMMARY"].includes(tab)&&<div className="calEmpty"><p>저장된 CASE입니다. 분석 버튼을 눌러 최신 trace를 확인하세요.</p></div>}{view&&tab==="FACT"&&<FactPanel view={view} audit={audit} save={saveAudit}/>} {view&&tab==="CORE"&&<CorePanel view={view}/>} {view&&tab==="FORTUNE"&&<FortunePanel view={view}/>} {view&&tab==="DOMAIN"&&<DomainPanel view={view}/>} {tab==="SELF REPORT"&&<SelfReport audit={audit} save={saveAudit}/>} {view&&tab==="TRACE"&&<TracePanel caseId={selected} steps={view.traceSteps}/>} {tab==="SUMMARY"&&<SummaryPanel/>}</>}</section></main>;
}

function NewCaseForm({form,update,submit,error,busy}:any){return <section className="calForm"><small>새 비공개 사례</small><h2>사전 메모를 먼저 남기고<br/>계산을 시작하세요.</h2><p>실명은 받지 않습니다. 입력과 결과는 이 컴퓨터의 gitignored 경로에만 저장됩니다.</p><form onSubmit={submit}><div className="calTwo"><label>성별<select value={form.gender} onChange={e=>update("gender",e.target.value)}><option value="female">여성</option><option value="male">남성</option></select></label><label>현재 관계<select value={form.relationshipStatus} onChange={e=>update("relationshipStatus",e.target.value)}>{RELATIONSHIP_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label></div><HybridDateField value={form.birthDate} onChange={v=>update("birthDate",v)} onError={()=>{}}/><label>달력<select value={form.calendarType} onChange={e=>update("calendarType",e.target.value)}><option value="solar">양력</option><option value="lunar">음력 · 준비 중</option></select></label><HybridTimeField value={form.birthTime??""} onChange={v=>update("birthTime",v)} onError={()=>{}}/><SearchSelect label="출생 국가" options={COUNTRY_OPTIONS} value={form.birthCountry} searchable onChange={v=>update("birthCountry",v)}/><SearchSelect label="출생 도시" options={cityOptions} value={form.birthCityKnown?form.birthCity??"":"UNKNOWN"} searchable disabled={form.birthCountry!=="KR"} onChange={v=>{update("birthCityKnown",v!=="UNKNOWN");update("birthCity",v==="UNKNOWN"?null:v);}}/><label>사전 메모<textarea value={form.preNotes??""} onChange={e=>update("preNotes",e.target.value)} placeholder="일하는 방식, 돈 성향, 관계 패턴, 큰 변화 등 결과를 보기 전 관찰을 기록하세요."/></label>{error&&<p className="calError">{error}</p>}<button className="calPrimary" disabled={busy}>{busy?"분석 중…":"분석하기"}</button></form></section>}
function CaseEditForm({form,update,save}:any){return <section className="auditSection calEdit"><h3>비공개 입력 수정</h3><p>출생 정보가 바뀌면 기존 결과는 stale로 표시되며 다시 분석해야 합니다.</p><div className="calTwo"><label>성별<select value={form.gender} onChange={e=>update("gender",e.target.value)}><option value="female">여성</option><option value="male">남성</option></select></label><label>현재 관계<select value={form.relationshipStatus} onChange={e=>update("relationshipStatus",e.target.value)}>{RELATIONSHIP_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label></div><HybridDateField value={form.birthDate} onChange={v=>update("birthDate",v)} onError={()=>{}}/><HybridTimeField value={form.birthTime??""} onChange={v=>update("birthTime",v)} onError={()=>{}}/><label>사전 메모<textarea value={form.preNotes??""} onChange={e=>update("preNotes",e.target.value)}/></label><button className="calPrimary" onClick={save}>비공개 입력 저장</button></section>}
function Section({title,children}:any){return <section className="auditSection"><h3>{title}</h3>{children}</section>}
function FactPanel({view,audit,save}:any){function assess(key:string,value:string){save({...audit,status:"REVIEWING",factAssessments:{...(audit?.factAssessments??{}),[key]:value}});}return <><Section title="FACT · 시간과 원국"><div className="statusBanner">{view.traceError?"TRACE_ERROR · 재구성 불일치":"PASS · production 결과와 trace 재구성 일치"}</div><dl className="factList">{Object.entries(view.facts).filter(([k])=>k!=="pillars"&&k!=="hiddenStems"&&k!=="tenGods").map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==="string"?v:JSON.stringify(v)}</dd><select aria-label={`${k} 평가`} value={audit?.factAssessments?.[k]??"UNCERTAIN"} onChange={e=>assess(k,e.target.value)}><option>PASS</option><option>FAIL</option><option>UNCERTAIN</option></select></div>)}</dl></Section><Section title="네 기둥"><div className="calPillars">{view.facts.pillars.map((p:any)=><article key={p.position}><small>{p.position}</small><b>{p.korean}</b><span>{p.hanja}</span></article>)}</div><details><summary>지장간과 십성 확인</summary>{pretty({hiddenStems:view.facts.hiddenStems,tenGods:view.facts.tenGods})}</details></Section></>}
function CorePanel({view}:any){return <><Section title="다섯 기운 · 단계별 수치"><div className="elementAudit">{view.elements.map((e:any)=><article key={e.element}><b>{elementNames[e.element]}</b><span>visible {e.raw}</span><span>native {e.native?.percentage?.toFixed?.(1)}%</span><span>adjusted {e.adjusted?.percentage?.toFixed?.(1)}%</span></article>)}</div><details><summary>왜 이렇게 나왔나요?</summary>{pretty(view.elements)}</details></Section><Section title="강약 재구성"><div className="bigMetrics"><b>original {view.strength.score}</b><b>adjusted {view.strength.adjusted?.score}</b><span>{view.strength.adjusted?.level}</span></div>{pretty(view.strength.evidence)}</Section><Section title="격국과 품질">{pretty(view.structure)}</Section><Section title="도움 기운 · 5개 원소"><div className="usefulAudit">{view.usefulGods.map((row:any)=><details key={row.element}><summary><b>{elementNames[row.element]??row.element}</b><span>{row.score?.toFixed?.(1)}</span></summary>{pretty(row)}</details>)}</div></Section><Section title="천간·지지 선호와 신살"><details><summary>천간 10개 / 지지 12개</summary>{pretty({stems:view.stemPreferences,branches:view.branchPreferences})}</details><details><summary>신살 presence/context</summary>{pretty(view.stars)}</details></Section></>}
function FortunePanel({view}:any){return <><Section title="10개 대운"><p>도움 흐름과 변화 활성도는 합산하지 않습니다.</p><div className="daeunAudit">{view.daeun.map((row:any,i:number)=><details key={i}><summary><b>{row.pillar?.korean??row.pillar?.hanja??`대운 ${i+1}`}</b><small>{row.pillar?.hanja} · {row.startAge}세</small></summary>{pretty(row)}</details>)}</div></Section><Section title="세운 / 월운 lazy summary"><p>세운 {view.seunCount}개 · 월운 {view.wolunCount}개</p><p>전체 월운은 초기 DOM에 렌더하지 않으며 trace step을 열 때만 불러옵니다.</p></Section></>}
function DomainPanel({view}:any){return <><Section title="분야별 흐름"><div className="domainAudit">{view.categories.slice(0,10).map((row:any,i:number)=><details key={i}><summary>{row.period?.pillar?.hanja??`구간 ${i+1}`}</summary>{pretty(row)}</details>)}</div></Section><Section title="Wellness · 전통 명리 참고">{pretty(view.wellness)}<p>질병·치료·수술·수명을 예측하지 않습니다.</p></Section><Section title="Children · 상징적 관계 지표">{pretty(view.children)}<p>실제 자녀 수나 성별 적중률이 아닙니다.</p></Section></>}
function SelfReport({audit,save}:any){const rows=audit?.assessments??[];function change(domain:AuditDomain,key:string,value:any){const current=rows.find((r:any)=>r.domain===domain)??{domain,classification:"UNKNOWN",mismatchTypes:[],notes:""};const next={...current,[key]:value};save({...audit,status:"REVIEWING",assessments:[...rows.filter((r:any)=>r.domain!==domain),next]});}return <Section title="실제 체감 비교"><p>FACT가 틀렸다면 하위 해석 평가보다 먼저 FACT_ERROR를 기록하세요.</p><div className="selfReport">{domains.map(domain=>{const row=rows.find((r:any)=>r.domain===domain)??{classification:"UNKNOWN",mismatchTypes:[],notes:""};return <article key={domain}><h4>{domain}</h4><select value={row.classification} onChange={e=>change(domain,"classification",e.target.value as AuditClassification)}><option value="MATCH">맞음</option><option value="PARTIAL">일부 맞음</option><option value="MISMATCH">안 맞음</option><option value="UNKNOWN">모름</option></select><select value={row.mismatchTypes?.[0]??""} onChange={e=>change(domain,"mismatchTypes",e.target.value?[e.target.value]:[])}><option value="">분류 없음</option>{mismatchTypes.map(type=><option key={type}>{type}</option>)}</select><textarea value={row.notes??""} onChange={e=>change(domain,"notes",e.target.value)} placeholder="관찰 메모"/></article>})}</div><label>전체 메모<textarea value={audit?.overallNotes??""} onChange={e=>save({...audit,overallNotes:e.target.value})}/></label></Section>}
function TracePanel({caseId,steps}:any){const [group,setGroup]=useState("전체"),[query,setQuery]=useState(""),[details,setDetails]=useState<Record<number,any>>({});const visible=steps.filter((s:any)=>(group==="전체"||s.group===group)&&`${s.title} ${s.id}`.toLowerCase().includes(query.toLowerCase()));async function load(index:number){if(details[index])return;const r=await fetch(`/api/dev/calibration/cases/${caseId}/trace/${index}`),body=r.ok?await r.json():{code:"TRACE_ERROR"};setDetails(v=>({...v,[index]:body}));}return <Section title="41단계 Trace"><div className="traceTools"><select value={group} onChange={e=>setGroup(e.target.value)}>{["전체","FACT","오행","강약","격국","용신","운세","분야","건강","자녀","AI INPUT"].map(x=><option key={x}>{x}</option>)}</select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="단계 검색"/></div><div className="traceList">{visible.map((s:any)=><details key={s.index} onToggle={e=>(e.currentTarget.open&&load(s.index))}><summary><span>{String(s.index).padStart(2,"0")} {s.title}</span><b className={s.status==="FAIL"?"fail":""}>{s.status}</b></summary>{details[s.index]?pretty(details[s.index]):<p>상세를 불러오는 중…</p>}</details>)}</div></Section>}
function SummaryPanel(){const [data,setData]=useState<any>();useEffect(()=>{fetch("/api/dev/calibration/summary").then(r=>r.json()).then(setData);},[]);return <Section title="다중 사례 패턴 요약"><p>사람의 순위를 만들거나 계수 변경을 추천하지 않습니다.</p>{data?pretty(data):<p>불러오는 중…</p>}</Section>}
