"use client";

import { useState } from "react";
import type { StructuredInterpretation } from "@/types/ai-interpretation";
import type { CurrentPeriodSelection, InterpretationUiState } from "@/types/customer-result";
import type { FortuneResult, SeunActivationPeriod, WolunActivationPeriod } from "@/types/fortune";
import type { CategoryFortunePeriod } from "@/types/category-fortune";
import type { SajuAnalysis, Element, PillarPosition } from "@/types/saju-analysis";
import type { StemPreferencesResult } from "@/types/stem-preferences";
import type { BranchPreferencesResult } from "@/types/branch-preferences";
import type { NobleSpecialStarsResult, StarDetection } from "@/types/noble-special-stars";
import type { SynthesisResult } from "@/types/useful-gods";
import { ACTIVATION_LABELS, FAVORABILITY_LABELS } from "@/lib/saju/presentation/format";

const ELEMENT: Record<Element, { name: string; hanja: string; meaning: string }> = {
  wood: { name: "나무", hanja: "木", meaning: "성장 · 시작 · 확장" }, fire: { name: "불", hanja: "火", meaning: "표현 · 추진 · 드러남" }, earth: { name: "흙", hanja: "土", meaning: "현실 · 관리 · 축적" }, metal: { name: "쇠", hanja: "金", meaning: "기준 · 결단 · 정리" }, water: { name: "물", hanja: "水", meaning: "생각 · 유연함 · 흐름" },
};
const POSITION: Record<PillarPosition, string> = { year: "년주", month: "월주", day: "일주", hour: "시주" };
const STEM_KO: Record<string, string> = { 甲: "갑", 乙: "을", 丙: "병", 丁: "정", 戊: "무", 己: "기", 庚: "경", 辛: "신", 壬: "임", 癸: "계" };
const BRANCH_KO: Record<string, string> = { 子: "자", 丑: "축", 寅: "인", 卯: "묘", 辰: "진", 巳: "사", 午: "오", 未: "미", 申: "신", 酉: "유", 戌: "술", 亥: "해" };
const MONTH_STORY: Record<string, string> = { 寅: "봄을 여는 첫 흐름", 卯: "봄의 두 번째 흐름", 辰: "봄을 마무리하는 흐름", 巳: "여름을 여는 첫 흐름", 午: "여름의 두 번째 흐름", 未: "여름을 마무리하는 흐름", 申: "가을을 여는 첫 흐름", 酉: "가을의 두 번째 흐름", 戌: "가을을 마무리하는 흐름", 亥: "겨울을 여는 첫 흐름", 子: "겨울의 두 번째 흐름", 丑: "겨울을 마무리하는 흐름" };
const STRENGTH_STORY: Record<string, string> = { 극약: "기운을 보충하고 충분히 쉬는 방식이 중요한 편", 태약: "혼자 밀어붙이기보다 도움을 활용할 때 힘이 나는 편", 신약: "주변 자원과 좋은 환경을 활용할 때 강점이 살아나는 편", 중화신약: "균형에 가깝지만 조금 약한 편", 중화신강: "균형에 가깝고 자기 힘이 조금 더 분명한 편", 신강: "스스로 결정하고 밀고 가는 힘이 강한 편", 태강: "강한 추진력을 조절하며 쓰는 것이 중요한 편", 극왕: "한 방향으로 집중되는 힘이 매우 뚜렷한 편" };
const STRUCTURE_STORY: Record<string, { title: string; keyword: string }> = {
  정관격: { title: "규칙과 기준을 중요하게 쓰는 구조", keyword: "분명한 기준" }, 편관격: { title: "책임과 긴장 속에서 실행력이 살아나는 구조", keyword: "실행력" }, 정재격: { title: "현실적인 성과와 꾸준한 관리를 중시하는 구조", keyword: "현실 감각" }, 편재격: { title: "기회와 거래의 흐름을 넓게 보는 구조", keyword: "기회 감각" }, 식신격: { title: "꾸준히 만들고 표현하며 성과를 쌓는 구조", keyword: "꾸준한 생산" }, 상관격: { title: "새롭게 표현하고 기존 방식을 바꾸는 구조", keyword: "표현력" }, 정인격: { title: "배움과 이해를 바탕으로 안정감을 만드는 구조", keyword: "깊은 이해" }, 편인격: { title: "독특한 관점과 전문성을 깊게 파고드는 구조", keyword: "전문성" }, 건록격: { title: "자기 힘과 독립성을 중심으로 움직이는 구조", keyword: "자립심" }, 양인격: { title: "결단력과 집중력이 강하게 드러나는 구조", keyword: "결단력" },
};
const TEN_GOD_STORY: Record<string, string> = { 비견: "나 자신과 동료의 기운", 겁재: "경쟁과 협력의 기운", 식신: "꾸준히 만들고 표현하는 기운", 상관: "새롭게 표현하고 바꾸는 기운", 정재: "안정적인 성과와 관리의 기운", 편재: "기회와 거래의 기운", 정관: "책임과 규칙의 기운", 편관: "도전과 실행의 기운", 정인: "배움과 안정의 기운", 편인: "통찰과 전문성의 기운" };
const STAR_STORY: Record<string, string> = { 태극귀인: "깊이 생각하고 원리를 탐구하는 성향을 보조합니다.", 학당귀인: "배움과 지식 습득의 흐름을 보조합니다.", 도화: "관계에서 매력과 표현이 드러나는 모습을 보조합니다.", 화개: "몰입과 예술적·정신적 관심을 보조합니다.", 귀문: "섬세한 감각과 직관의 경향을 보조합니다.", 공망: "비어 있는 지점을 다른 방식으로 채우는 흐름을 살핍니다.", 현침: "정교함과 예민한 표현의 경향을 보조합니다.", 백호: "강한 집중과 긴장감이 나타나는 맥락을 보조합니다.", 괴강: "결단과 독립성이 강하게 나타나는 맥락을 보조합니다." };
const FAVORABILITY: Record<string, string> = FAVORABILITY_LABELS;
const ACTIVITY: Record<string, string> = ACTIVATION_LABELS;
const SUPPORT: Record<string, string> = { VERY_SUPPORTIVE: "매우 든든함", SUPPORTIVE: "든든함", MODERATELY_SUPPORTIVE: "다소 도움", MIXED: "여러 흐름이 섞임", LOW_SUPPORT: "도움이 적은 편", PRESSURED: "부담이 있는 편" };
const ALIGNMENT: Record<string, string> = { VERY_HIGH_ALIGNMENT: "매우 잘 어울림", HIGH_ALIGNMENT: "잘 어울리는 편", FAVORABLE_ALIGNMENT: "비교적 잘 어울림", MIXED_ALIGNMENT: "여러 방향이 섞임", LOW_ALIGNMENT: "어울림이 낮은 편", VERY_LOW_ALIGNMENT: "어울림이 매우 낮은 편" };
const STRUCTURE_STATUS: Record<string, string> = { ESTABLISHED: "뚜렷하게 성립", UNEXPOSED: "안쪽에 자리함", MIXED: "여러 흐름이 함께 있음", SPECIAL_CANDIDATE: "특수 구조 가능성", UNRESOLVED: "판단 유보", CLEAN: "안정적", SUPPORTED: "지지받음", DAMAGED: "조정할 부분 있음", RESCUED: "보완됨" };
const RESULT_NAV = [["story", "나의 이야기"], ["elements", "다섯 기운"], ["balance", "힘 쓰는 방식"], ["daeun", "큰 흐름"], ["seun", "올해"], ["wolun", "월별"], ["categories", "삶의 분야"], ["interpretation", "AI 해석"], ["professional", "전문 분석"]] as const;

const round = (value: number | null | undefined, digits = 0) => value == null ? "—" : value.toFixed(digits);
const date = (value?: string) => value ? new Intl.DateTimeFormat("ko-KR", { month: "numeric", day: "numeric" }).format(new Date(value)) : "—";
const periodYear = (value?: string) => value ? new Date(value).getUTCFullYear() : null;
const pillarKo = (stem?: string | null, branch?: string | null) => `${STEM_KO[stem ?? ""] ?? stem ?? ""}${BRANCH_KO[branch ?? ""] ?? branch ?? ""}`;
const supportLabel = (level?: string | null) => SUPPORT[level ?? ""] ?? FAVORABILITY[level ?? ""] ?? ALIGNMENT[level ?? ""] ?? level ?? "흐름 확인 중";
const activityLabel = (level?: string | null) => ACTIVITY[level ?? ""] ?? level ?? "변화 확인 중";

function Section({ id, eyebrow, title, intro, children }: { id: string; eyebrow?: string; title: string; intro?: string; children: React.ReactNode }) { return <section id={id} className="storySection" aria-labelledby={`${id}-title`}>{eyebrow && <span className="sectionEyebrow">{eyebrow}</span>}<h2 id={`${id}-title`}>{title}</h2>{intro && <p className="storyIntro">{intro}</p>}{children}</section>; }
function ScoreDetail({ label, score, level, tone = "support" }: { label: string; score?: number | null; level?: string | null; tone?: "support" | "activity" | "pressure" }) { return <div className={`metric ${tone}`}><span>{label}</span><strong>{round(score)}<small> / 100</small></strong>{level && <em>{tone === "activity" || tone === "pressure" ? activityLabel(level) : supportLabel(level)}</em>}</div>; }
function FlowWords({ support, activity }: { support?: string | null; activity?: string | null }) { return <div className="flowWords"><span><small>도움의 정도</small><b>{supportLabel(support)}</b></span><span><small>변화의 크기</small><b>{activityLabel(activity)}</b></span></div>; }
function Evidence({ ids }: { ids: string[] }) { const label = (id: string) => id.includes("FAVORABILITY") ? "선택한 기간에 도움이 되는 흐름을 반영했습니다." : id.includes("ACTIVATION") ? "변화와 움직임이 얼마나 활발한지 반영했습니다." : id.includes("ALIGNMENT") ? "현재 흐름과 타고난 다섯 기운의 관계를 반영했습니다." : id.includes("CATEGORY") ? "생활 분야별 도움과 변화 정도를 따로 반영했습니다." : id.includes("USEFUL_GOD") ? "균형을 돕는 여러 관점의 공통점과 차이를 함께 반영했습니다." : "검증된 계산 결과를 근거로 사용했습니다."; return <details className="evidence"><summary>이 설명의 근거 보기</summary><ul>{ids.map((id) => <li key={id}><span>{label(id)}</span>{process.env.NODE_ENV !== "production" && <code>{id}</code>}</li>)}</ul></details>; }

function StoryHero({ analysis, interpretation, onRestart }: { analysis: SajuAnalysis; interpretation: InterpretationUiState; onRestart?: () => void }) {
  const structure = analysis.structure.primary?.type ?? "", strength = analysis.strength.adjusted.level ?? "";
  const synthesis = analysis.usefulGods.synthesis as SynthesisResult, ai = interpretation.status === "completed" ? interpretation.report : null;
  const helpful = synthesis.status === "implemented" ? [...synthesis.primaryElements, ...synthesis.secondaryElements, ...synthesis.favorableElements].slice(0, 2) : [];
  const summary = ai?.summary ?? `${STRENGTH_STORY[strength] ?? strength}입니다. ${STRUCTURE_STORY[structure]?.title ?? `${structure}의 특징을 함께 지니고 있습니다.`}`;
  const keywords = [STRUCTURE_STORY[structure]?.keyword, strength.includes("강") || strength.includes("왕") ? "자기 추진력" : "환경 활용", ...helpful.map((element) => `${ELEMENT[element].name}의 흐름`)].filter((item): item is string => Boolean(item)).slice(0, 4);
  return <header className="storyHero"><div className="heroTop"><span className="sectionEyebrow">POSTPOST RESULT</span>{onRestart && <button className="restartButton" onClick={onRestart}>다시 입력하기</button>}</div><p className="heroKicker">타고난 기질부터 지금의 흐름까지</p><h1>{analysis.person.name}님의<br />사주 이야기</h1><p className="heroSummary">{summary}</p><div className="keywordRow">{keywords.map((keyword) => <span key={keyword}>#{keyword.replaceAll(" ", "")}</span>)}</div><a className="professionalLink" href="#professional">전문 원국은 아래에서 자세히 볼 수 있어요</a></header>;
}

function AtAGlance({ analysis, interpretation }: { analysis: SajuAnalysis; interpretation: InterpretationUiState }) {
  const structure = analysis.structure.primary?.type ?? "", ai = interpretation.status === "completed" ? interpretation.report : null;
  const strength = STRENGTH_STORY[analysis.strength.adjusted.level ?? ""] ?? analysis.strength.adjusted.level;
  const cards = [{ label: "나의 기본 성향", text: ai?.headline ?? STRUCTURE_STORY[structure]?.title ?? `${structure}의 특징이 중심을 이룹니다.` }, { label: "강점", text: ai?.highlights[0] ?? `${strength}이라서 자신의 리듬과 주변 자원을 함께 살릴 때 강점이 선명해집니다.` }, { label: "주의할 점", text: ai?.cautions[0] ?? "한 시기의 점수보다 도움의 방향과 변화의 크기를 나누어 살펴보세요." }];
  return <Section id="story" eyebrow="한눈에 보는 나" title="먼저, 이런 사람으로 읽혀요" intro="전문 용어보다 지금 이해하기 쉬운 말로 핵심부터 정리했습니다."><div className="glanceList">{cards.map((card, index) => <article key={card.label}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{card.label}</h3><p>{card.text}</p></div></article>)}</div></Section>;
}

function FiveElements({ analysis }: { analysis: SajuAnalysis }) {
  const native = analysis.fiveElements.nativeStrength, adjusted = analysis.fiveElements.adjustedStrength.elements;
  return <Section id="elements" eyebrow="나를 이루는 다섯 기운" title="내 안의 기운은 이렇게 어우러져요" intro="높고 낮음은 좋고 나쁨이 아니라, 내가 익숙하게 쓰는 방식의 차이입니다."><div className="elementStory">{(Object.keys(ELEMENT) as Element[]).map((element) => <article key={element}><div><span className={`elementOrb ${element}`}>{ELEMENT[element].name}</span><p><b>{ELEMENT[element].meaning}</b><small>{ELEMENT[element].hanja}의 기운</small></p></div><i aria-hidden="true" style={{ "--bar": `${Math.min(100, adjusted?.[element].percentage ?? 0)}%` } as React.CSSProperties} /><span className="srOnly">{ELEMENT[element].name} 관계 반영 분포 {round(adjusted?.[element].percentage, 1)}</span></article>)}</div><details className="detailDisclosure"><summary>기운의 수치 자세히 보기</summary><div className="elementNumbers">{(Object.keys(ELEMENT) as Element[]).map((element) => <p key={element}><b>{ELEMENT[element].name}</b><span>기본 {round(native?.[element].percentage, 1)}</span><span>관계 반영 {round(adjusted?.[element].percentage, 1)}</span></p>)}</div></details></Section>;
}

function BalanceAndHelpful({ analysis }: { analysis: SajuAnalysis }) {
  const strength = analysis.strength.adjusted.level ?? "판단 대기", structure = analysis.structure.primary?.type ?? "격국 판단 유보", synthesis = analysis.usefulGods.synthesis as SynthesisResult;
  if (synthesis.status !== "implemented") return null;
  const helpful = Array.from(new Set<Element>([...synthesis.primaryElements, ...synthesis.secondaryElements, ...synthesis.favorableElements])), conditional = synthesis.conditionalElements;
  return <><Section id="balance" eyebrow="내가 힘을 쓰는 방식" title={STRENGTH_STORY[strength] ?? strength} intro={STRUCTURE_STORY[structure]?.title ?? `${structure}의 특징을 바탕으로 힘을 씁니다.`}><div className="storyCallout"><span>쉽게 말하면</span><p>내 힘만으로 밀어붙이는지, 주변의 도움과 환경을 활용하는지에 따라 결과가 달라질 수 있어요. 관계까지 반영한 최종 강약을 기준으로 설명합니다.</p></div><details className="detailDisclosure"><summary>강약과 구조 수치 보기</summary><div className="detailPair"><ScoreDetail label="관계 반영 강약" score={analysis.strength.adjusted.score} level={strength} /><div className="termCard"><small>전문 분류</small><b>{strength}</b><span>{structure}</span><em>{STRUCTURE_STATUS[analysis.structure.classificationStatus] ?? analysis.structure.classificationStatus}</em></div></div></details></Section><Section id="helpful" eyebrow="나에게 도움이 되는 흐름" title="이 기운을 잘 활용해 보세요" intro={`현재 사주에서는 ${helpful.map((item) => ELEMENT[item].name).join("·") || "균형을 보완하는"}의 기운을 비교적 잘 활용합니다.`}><div className="helpfulFlow"><div><small>우선 도움이 되는 기운</small><strong>{helpful.map((item) => ELEMENT[item].name).join(" · ") || "해당 없음"}</strong></div><div><small>상황에 따라 활용할 기운</small><strong>{conditional.map((item) => ELEMENT[item].name).join(" · ") || "해당 없음"}</strong></div></div><details className="detailDisclosure"><summary>전문 용신 분석 보기</summary><div className="perspectives">{[["억부", analysis.usefulGods.eokbu.primaryElements], ["조후", analysis.usefulGods.johu.elementPreferences.slice(0, 2).map((v) => v.element)], ["통관", analysis.usefulGods.tonggwan.elementPreferences.slice(0, 2).map((v) => v.element)], ["병약", analysis.usefulGods.byeongyak.elementPreferences.slice(0, 2).map((v) => v.element)], ["격국", analysis.usefulGods.structure.elementPreferences.slice(0, 2).map((v) => v.element)]].map(([label, values]) => <div key={label as string}><b>{label as string}</b><span>{(values as Element[]).map((value) => ELEMENT[value].name).join(" · ") || "해당 없음"}</span></div>)}</div><Evidence ids={synthesis.evidence.slice(0, 4)} /></details></Section></>;
}

function DaeunStory({ analysis, current }: { analysis: SajuAnalysis; current: CurrentPeriodSelection }) {
  const fortune = analysis.fortune as FortuneResult;
  const [daeunIndex, setDaeunIndex] = useState(current.daeunIndex ?? 0);
  const periods = fortune.daeun.status === "implemented" ? fortune.daeun.periods.map((item) => ({ ...item, startInstant: item.sourcePeriod.startInstant, endInstant: item.sourcePeriod.endInstant })) : [];
  const selected = periods.find((item) => item.index === daeunIndex) ?? periods[0];
  return <Section id="daeun" eyebrow="인생의 큰 흐름" title="시간이 바뀌면, 힘을 쓰는 방식도 달라져요" intro="나이와 기간을 먼저 보고, 간지는 전문 정보로 작게 표시했습니다."><div className="storyTimeline" role="list" aria-label="대운 타임라인">{periods.map((period) => <button role="listitem" aria-pressed={period.index === selected?.index} className={period.index === selected?.index ? "active" : ""} key={period.index} onClick={() => setDaeunIndex(period.index)}><span>{period.sourcePeriod.ageRange}</span><b>{periodYear(period.startInstant)}~{periodYear(period.endInstant)}</b><small>{pillarKo(period.pillar.stem, period.pillar.branch)} · {period.pillar.stem}{period.pillar.branch}</small></button>)}</div>{selected && <article className="selectedStory" aria-live="polite"><span className="storyLabel">선택한 큰 흐름</span><h3>{selected.sourcePeriod.ageRange}, {supportLabel(selected.preference.role)}이 느껴지는 시기</h3><p>도움의 흐름은 {supportLabel(selected.preference.role)}이고, 변화는 {activityLabel(selected.activation.level)}입니다. 새로운 선택은 두 흐름을 따로 살펴보세요.</p><FlowWords support={selected.preference.role} activity={selected.activation.level} /><details><summary>수치와 전문 정보 보기</summary><div className="detailPair"><ScoreDetail label="지원 흐름" score={selected.preference.baseFavorabilityScore} level={selected.preference.role} /><ScoreDetail label="변화 정도" score={selected.activation.score} level={selected.activation.level} tone="activity" /></div><p className="technicalLine">{pillarKo(selected.pillar.stem, selected.pillar.branch)}({selected.pillar.stem}{selected.pillar.branch}) · 십성 {TEN_GOD_STORY[selected.tenGodProfile.stemTenGod] ?? selected.tenGodProfile.stemTenGod} · 상호작용 {selected.interactions.length}개</p></details></article>}</Section>;
}

function YearAndMonth({ analysis, current, year, onYearChange }: { analysis: SajuAnalysis; current: CurrentPeriodSelection; year: number; onYearChange: (year: number) => void }) {
  const fortune = analysis.fortune as FortuneResult;
  const seunAll = fortune.seun.status === "implemented" ? fortune.seun.periods ?? [] : [];
  const seun = seunAll.find((item) => item.year === year);
  const wolun = fortune.wolun.status === "implemented" ? (fortune.wolun.periods ?? []).filter((item) => item.seunYear === year).slice(0, 12) : [];
  return <><Section id="seun" eyebrow="올해와 가까운 해의 흐름" title={`${year}년은 이렇게 흘러가요`} intro="연도를 선택하면 아래 월별 흐름과 삶의 분야도 함께 바뀝니다."><div className="yearPicker" role="list" aria-label="세운 연도 선택">{seunAll.slice(0, 18).map((period) => <button role="listitem" aria-pressed={period.year === year} className={period.year === year ? "active" : ""} key={period.year} onClick={() => onYearChange(period.year)}><b>{period.year}{period.year === current.seunYear && <small className="currentBadge">현재</small>}</b><span>{pillarKo(period.pillar.stem, period.pillar.branch)}</span></button>)}</div>{seun && <SeunNarrative period={seun} />}</Section><WolunStory periods={wolun} /></>;
}

function SeunNarrative({ period }: { period: SeunActivationPeriod }) { return <article className="selectedStory" aria-live="polite"><span className="storyLabel">{pillarKo(period.pillar.stem, period.pillar.branch)}의 해</span><h3>도움은 {supportLabel(period.preference.role)}, 변화는 {activityLabel(period.activation.level)}</h3><p>좋고 나쁨 하나로 합치지 않고, 나를 돕는 정도와 실제 움직임의 크기를 따로 읽습니다.{period.daeunSegments.length > 1 && " 이 해에는 큰 흐름이 바뀌는 경계가 포함됩니다."}</p><FlowWords support={period.preference.role} activity={period.activation.level} /><details><summary>수치와 간지 보기</summary><div className="detailPair"><ScoreDetail label="지원 흐름" score={period.preference.baseFavorabilityScore} level={period.preference.role} /><ScoreDetail label="변화 정도" score={period.activation.score} level={period.activation.level} tone="activity" /></div><p className="technicalLine">{pillarKo(period.pillar.stem, period.pillar.branch)}({period.pillar.stem}{period.pillar.branch}) · 현재 대운 {period.activeDaeunPillar ?? "경계 밖"}</p></details></article>; }

function WolunStory({ periods }: { periods: WolunActivationPeriod[] }) { return <Section id="wolun" eyebrow="월별 흐름" title="절기로 이어지는 열두 장면" intro="월운은 양력 1일이 아니라 절기 경계에서 바뀝니다. 실제 날짜를 함께 확인해 주세요."><div className="monthStoryList">{periods.map((period) => <article key={`${period.seunYear}-${period.indexInSeun}`}><div className="monthTitle"><span>{MONTH_STORY[period.solarMonthBranch] ?? "계절의 흐름"}</span><small>{date(period.period.startInstant)} ~ {date(period.period.endInstant)}</small></div><p>도움은 <b>{supportLabel(period.preference.role)}</b>, 변화는 <b>{activityLabel(period.activation.level)}</b>인 구간입니다.</p><details><summary>수치와 간지</summary><div className="monthDetail"><span>{BRANCH_KO[period.solarMonthBranch]}월({period.solarMonthBranch}月) · {pillarKo(period.pillar.stem, period.pillar.branch)}({period.pillar.stem}{period.pillar.branch})</span><b>지원 {round(period.preference.baseFavorabilityScore)} · 변화 {round(period.activation.score)}</b></div></details></article>)}</div></Section>; }

function CategoryStories({ analysis, selectedYear, current }: { analysis: SajuAnalysis; selectedYear: number; current: CurrentPeriodSelection }) {
  const fortune = analysis.fortune as FortuneResult;
  if (fortune.categories.status !== "implemented" || fortune.synthesis.status !== "implemented") return null;
  const axes = fortune.synthesis.seun.find((item) => item.context.seunYear === selectedYear) ?? fortune.synthesis.daeun[current.daeunIndex ?? 0] ?? fortune.synthesis.seun[0];
  const category = fortune.categories.seun.find((item) => item.synthesisId === axes?.synthesisId) ?? fortune.categories.daeun.find((item) => item.synthesisId === axes?.synthesisId) ?? fortune.categories.seun[0];
  if (!category || !axes) return null;
  return <><Section id="year-flow" eyebrow="한 해를 읽는 세 가지 기준" title={`${selectedYear}년 흐름을 한 문장으로 합치지 않아요`} intro="도움, 변화, 오행의 어울림은 서로 다른 의미이므로 각각 살펴봅니다."><div className="axisStories"><article><small>나를 돕는 흐름</small><b>{supportLabel(axes.favorability.level)}</b><span>선택과 실행을 얼마나 받쳐주는지</span></article><article><small>변화의 움직임</small><b>{activityLabel(axes.activation.level)}</b><span>사건과 선택이 얼마나 활발한지</span></article><article><small>기운의 어울림</small><b>{supportLabel(axes.transformationAlignment.level)}</b><span>현재 오행이 나와 얼마나 맞물리는지</span></article></div><details className="detailDisclosure"><summary>세 축의 수치 보기</summary><div className="detailTriple"><ScoreDetail label="지원 흐름" score={axes.favorability.score} level={axes.favorability.level} /><ScoreDetail label="변화 활성도" score={axes.activation.score} level={axes.activation.level} tone="activity" /><ScoreDetail label="오행 정렬도" score={axes.transformationAlignment.adjustedScore} level={axes.transformationAlignment.level} /></div></details></Section><Section id="categories" eyebrow="내 삶의 분야별 흐름" title={`${selectedYear}년, 생활 속에서는 이렇게 보여요`} intro="숫자보다 결론을 먼저 읽고, 필요한 분야만 펼쳐 보세요."><CategoryGrid category={category} /><Evidence ids={category.evidence.slice(0, 4)} /></Section></>;
}

function CategoryGrid({ category }: { category: CategoryFortunePeriod }) {
  const items = [["재물", "돈을 모으고 쓰는 흐름", category.wealth], ["사업", "기회를 만들고 거래하는 흐름", category.business], ["직장", "조직과 책임 안에서 움직이는 흐름", category.career], ["관계", "사람을 만나고 관계를 이어가는 흐름", category.relationship], ["공부", "배우고 익혀 내 것으로 만드는 흐름", category.study], ["변화", "이동하고 새롭게 전환하는 흐름", category.change]] as const;
  return <div className="categoryStories">{items.map(([label, description, item]) => <details key={label}><summary><span><b>{label}</b><small>{description}</small></span><em>{supportLabel(item.supportLevel)} · 변화 {activityLabel(item.activityLevel)}</em></summary><p>현재 {label} 분야는 도움이 <b>{supportLabel(item.supportLevel)}</b>이고 움직임은 <b>{activityLabel(item.activityLevel)}</b>입니다.</p><div className="detailPair"><ScoreDetail label="지원도" score={item.supportScore} level={item.supportLevel} /><ScoreDetail label="활성도" score={item.activityScore} level={item.activityLevel} tone="activity" /></div>{label === "재물" && <WealthDetails category={category} />}{label === "관계" && <RelationshipDetails category={category} />}</details>)}</div>;
}
function WealthDetails({ category }: { category: CategoryFortunePeriod }) { return <div className="subMetrics"><ScoreDetail label="수입 기회" score={category.wealth.incomeOpportunity.score} level={category.wealth.incomeOpportunity.level} /><ScoreDetail label="사업 매출" score={category.wealth.businessRevenue.score} level={category.wealth.businessRevenue.level} /><ScoreDetail label="안정적 현금흐름" score={category.wealth.stableCashflow.score} level={category.wealth.stableCashflow.level} /><ScoreDetail label="자산 축적" score={category.wealth.assetAccumulation.score} level={category.wealth.assetAccumulation.level} /><ScoreDetail label="지출 압력" score={category.wealth.expensePressure.score} level={category.wealth.expensePressure.level} tone="pressure" /><ScoreDetail label="확장·투자 활성도" score={category.wealth.expansionInvestment.score} level={category.wealth.expansionInvestment.level} tone="activity" /></div>; }
function RelationshipDetails({ category }: { category: CategoryFortunePeriod }) { return <div className="subMetrics"><ScoreDetail label="기회" score={category.relationship.opportunity.score} level={category.relationship.opportunity.level} /><ScoreDetail label="안정성" score={category.relationship.stability.score} level={category.relationship.stability.level} /><ScoreDetail label="공식화 지원" score={category.relationship.formalizationSupport.score} level={category.relationship.formalizationSupport.level} /></div>; }

function Interpretation({ state, onRequest, onRetry }: { state: InterpretationUiState; onRequest: () => void; onRetry: () => void }) {
  const failureCopy = state.status === "failed" && state.error.code === "NETWORK_ERROR" ? "네트워크 연결 문제로 AI 해석을 불러오지 못했어요." : "AI 해석 서비스에서 응답을 받지 못했어요.";
  return <Section id="interpretation" eyebrow="AI 상세 해석" title="계산 근거를 이야기로 이어 읽어보세요" intro="검증된 계산 결과를 바꾸지 않고, 이해하기 쉬운 문장으로 연결합니다.">{state.status === "not_requested" && <div className="interpretationPrompt"><p>타고난 성향과 선택한 시기의 흐름을 짧은 챕터로 정리할 수 있어요.</p><button onClick={onRequest}>나의 상세 이야기 만들기</button></div>}{state.status === "pending" && <div className="skeleton" role="status" aria-label="AI 해석 생성 중"><i /><i /><i /></div>}{state.status === "failed" && <div className="errorPanel" role="alert"><strong>{failureCopy}</strong><p>사주 계산 결과는 정상이며 위 내용을 계속 확인할 수 있습니다.</p><button onClick={onRetry}>해석 다시 시도</button></div>}{state.status === "completed" && <Report report={state.report} />}</Section>;
}
function Report({ report }: { report: StructuredInterpretation }) { return <div className="reportChapters"><header><span>한 문장 요약</span><h3>{report.headline}</h3><p>{report.summary}</p></header>{report.highlights.length > 0 && <article className="highlightChapter"><span>지금 기억할 점</span><ul>{report.highlights.map((item) => <li key={item}>{item}</li>)}</ul></article>}{report.sections.map((section, index) => <article key={section.id}><span>CHAPTER {String(index + 1).padStart(2, "0")}</span><h4>{section.title}</h4><p>{section.body}</p><Evidence ids={section.evidenceIds} /></article>)}{report.cautions.length > 0 && <article className="cautionChapter"><span>천천히 살펴볼 점</span><ul>{report.cautions.map((item) => <li key={item}>{item}</li>)}</ul></article>}<p className="disclaimer">{report.disclaimer}</p></div>; }

function ProfessionalAnalysis({ analysis }: { analysis: SajuAnalysis }) {
  const tenGods = analysis.tenGods.value, hidden = analysis.hiddenStems.value, stages = analysis.twelveStages.value;
  const stems = analysis.stemPreferences as StemPreferencesResult, branches = analysis.branchPreferences as BranchPreferencesResult;
  const stars = analysis.nobleAndSpecialStars as NobleSpecialStarsResult;
  const detected: StarDetection[] = stars.status === "implemented" ? [stars.nobleStars, stars.peachBlossom, stars.travelHorse, stars.flowerCanopy, stars.ghostGate, stars.wonjin, stars.needle, stars.yangBlade, stars.goegang, stars.whiteTiger].flat() : [];
  return <section id="professional" className="professionalSection"><details><summary><span><small>전문 분석</small><b>원국과 명리 용어를 자세히 보고 싶다면</b></span><em>펼쳐 보기</em></summary><div className="professionalBody"><h2>사주 원국</h2><p>이 영역은 전문 정보를 확인하고 싶은 분을 위한 상세 자료입니다.</p><div className="natalGrid">{(["year", "month", "day", "hour"] as PillarPosition[]).map((position) => { const pillar = analysis.pillars[position], branchHidden = hidden?.branches[position], hiddenStems = branchHidden ? [branchHidden.mainQi, branchHidden.middleQi, branchHidden.residualQi].filter((item): item is NonNullable<typeof item> => item != null) : []; return <article className={`natalPillar ${position === "day" ? "dayMaster" : ""}`} key={position}><span>{POSITION[position]}{position === "day" && <b>나</b>}</span><strong aria-label={`${pillar.stem ?? "미상"} ${pillar.branch ?? "미상"}`}>{pillar.stem}<br />{pillar.branch}</strong><small>{pillarKo(pillar.stem, pillar.branch)}</small><dl><div><dt>십성</dt><dd>{tenGods?.heavenlyStems[position]?.korean ?? "—"}</dd></div><div><dt>지장간</dt><dd>{hiddenStems.map((item) => item.stem).join(" · ") || "—"}</dd></div><div><dt>십이운성</dt><dd>{stages?.stages[position]?.korean ?? "—"}</dd></div></dl></article>; })}</div><div className="professionalGrid"><article><h3>격국 상세</h3><p>{analysis.structure.primary?.type ?? "판단 유보"}</p><span>{STRUCTURE_STATUS[analysis.structure.classificationStatus] ?? analysis.structure.classificationStatus} · {STRUCTURE_STATUS[analysis.structure.qualityEvaluation.integrity] ?? analysis.structure.qualityEvaluation.integrity}</span></article><article><h3>선호 천간·지지</h3><p>{stems.status === "implemented" ? stems.rankedStems.slice(0, 4).map((item) => `${STEM_KO[item]}(${item})`).join(" · ") : "—"}</p><span>{branches.status === "implemented" ? branches.rankedBranches.slice(0, 4).map((item) => `${BRANCH_KO[item]}(${item})`).join(" · ") : "—"}</span></article></div><h3>보조적으로 보이는 특징</h3><div className="starCards">{detected.length ? detected.map((star) => <article key={star.id}><b>{star.label}</b><p>{STAR_STORY[star.label] ?? "전통 명리에서 성향과 흐름을 보조해 살피는 지표입니다."}</p></article>) : <p>두드러진 보조 지표가 없습니다.</p>}</div><p className="professionalNotice">신살은 하나의 항목만으로 길흉이나 사건을 단정하지 않는 보조 지표입니다.</p></div></details></section>;
}

export function CustomerResult({ analysis, current, interpretation, onInterpret, onRetry, onRestart }: { analysis: SajuAnalysis; current: CurrentPeriodSelection; interpretation: InterpretationUiState; onInterpret: () => void; onRetry: () => void; onRestart?: () => void }) {
  const fortune = analysis.fortune as FortuneResult;
  const firstYear = fortune.seun.status === "implemented" ? fortune.seun.periods?.[0]?.year : undefined;
  const [selectedYear, setSelectedYear] = useState(current.seunYear ?? firstYear ?? 0);
  return <div className="customerResult"><StoryHero analysis={analysis} interpretation={interpretation} onRestart={onRestart} /><nav className="resultNav" aria-label="결과 빠른 이동">{RESULT_NAV.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav><main className="resultBody"><AtAGlance analysis={analysis} interpretation={interpretation} /><FiveElements analysis={analysis} /><BalanceAndHelpful analysis={analysis} /><DaeunStory analysis={analysis} current={current} /><YearAndMonth analysis={analysis} current={current} year={selectedYear} onYearChange={setSelectedYear} /><CategoryStories analysis={analysis} current={current} selectedYear={selectedYear} /><Interpretation state={interpretation} onRequest={onInterpret} onRetry={onRetry} /><ProfessionalAnalysis analysis={analysis} />{process.env.NODE_ENV !== "production" && <details className="debugPanel"><summary>개발자 진단 정보</summary><p>규칙 버전 {analysis.rulesetVersion} · 엔진 {analysis.engineMetadata.engineVersion}</p><pre>{JSON.stringify({ current, analysis, interpretation }, null, 2)}</pre></details>}</main></div>;
}
