"use client";
import { useState } from "react";
import { customerElement, customerTerm } from "@/rules/customer-terminology.v1";
import { LIFETIME_REPORT_V2 } from "@/rules/lifetime-report.v2";
import type { RelationshipStatus, StructuredInterpretation } from "@/types/ai-interpretation";
import type { CurrentPeriodSelection, InterpretationUiState } from "@/types/customer-result";
import type { CategoryFortunePeriod } from "@/types/category-fortune";
import type { FortuneResult } from "@/types/fortune";
import type { SajuAnalysis, Element, PillarPosition } from "@/types/saju-analysis";
import type { WellnessResult } from "@/types/wellness";
import type { ChildrenFortuneResult } from "@/types/children-fortune";

const ELEMENTS: Element[] = ["wood", "fire", "earth", "metal", "water"];
const ELEMENT_THEME: Record<Element, string> = { wood: "성장과 유연함", fire: "표현과 추진", earth: "현실과 관리", metal: "기준과 정리", water: "생각과 회복" };
const RELATIONSHIP_COPY: Record<RelationshipStatus, string> = { SINGLE: "새로운 사람을 만날 때 무엇을 중요하게 보는지 살펴봅니다.", DATING: "연애하면서 마음을 어떻게 표현하고 다툼을 어떻게 푸는지 살펴봅니다.", MARRIED: "배우자와 집안일과 책임을 어떻게 나누면 좋은지 살펴봅니다." };
const RELATIONSHIP_DETAIL: Record<RelationshipStatus, string[]> = {
  SINGLE:["새로운 사람을 만날 때는 첫 느낌보다 말과 행동이 같은지를 살펴봅니다.","처음에는 마음을 크게 드러내지 않지만 믿음이 생기면 행동으로 꾸준히 보여 줍니다.","서로 혼자 있는 시간을 존중하고, 필요할 때 곁에 있어 주는 관계가 편합니다.","상대가 내 마음을 알아서 알기를 기다리지 말고, 내가 원하는 것을 말로 알려 주세요."],
  DATING:["연애할 때는 사랑하는 마음만큼 서로 표현하는 방법을 이해하는 것이 중요합니다.","다투면 혼자 생각을 정리한 뒤 말하려는 편입니다. 생각할 시간이 필요하다고 먼저 알려 주세요.","오래 만나려면 약속을 지키고 생활 방식과 맡을 일을 함께 정하는 것이 중요합니다.","내 말이 맞다고 설득하기 전에 상대의 생각부터 물어보세요."],
  MARRIED:["결혼 생활에서는 내가 맡은 일을 꾸준히 해내려는 모습이 먼저 보입니다.","가족에게 필요한 일을 미리 챙기지만, 혼자 다 맡으면 서운한 마음이 쌓일 수 있습니다.","일정, 집안일, 돈 문제를 배우자와 함께 정할 때 생활이 더 편해집니다.","오래 함께 살아도 각자 혼자 쉬는 시간과 서로 이야기하는 시간을 남겨 두세요."],
};
const STRENGTH_COPY: Record<string, string> = { 극약: "충분히 쉬고 기운을 보충한 뒤 움직이는 편이 좋습니다.", 태약: "혼자 버티기보다 필요한 도움을 받을 때 일을 더 수월하게 풀어갑니다.", 신약: "좋은 환경과 믿을 만한 사람이 곁에 있을 때 제 실력을 더 잘 냅니다.", 중화신약: "균형에 가깝지만, 주변의 도움을 받으면 일을 조금 더 수월하게 해낼 수 있습니다.", 중화신강: "균형에 가깝고, 필요할 때는 스스로 방향을 정해 움직이는 힘도 있습니다.", 신강: "자기 판단으로 방향을 정하고 끝까지 밀고 가는 힘이 분명합니다.", 태강: "추진력은 충분합니다. 다만 속도를 조절할 때 결과가 더 안정적입니다.", 극왕: "한곳에 힘을 집중하는 데 능합니다. 필요할 때는 다른 사람과 역할을 나누는 연습도 중요합니다." };
const ACTIVITY: Record<string, string> = { LOW: "잔잔함", MODERATE: "보통", HIGH: "큰 편", VERY_HIGH: "매우 큰 편" };
const SUPPORT: Record<string, string> = { PRIMARY_FAVORABLE: "매우 우호적", STRONG_FAVORABLE: "우호적", FAVORABLE: "비교적 우호적", CONDITIONAL: "조건부", NEUTRAL: "중립적", CAUTION: "주의 필요", UNFAVORABLE: "부담이 있는 편", VERY_SUPPORTIVE: "매우 든든함", SUPPORTIVE: "든든함", MODERATELY_SUPPORTIVE: "다소 도움", MIXED: "여러 흐름이 섞임", LOW_SUPPORT: "도움이 적은 편", PRESSURED: "부담이 있는 편" };
const STEM_COPY: Record<string, string> = { 甲: "갑목 · 큰 나무의 기운", 乙: "을목 · 유연한 풀과 덩굴의 기운", 丙: "병화 · 밝은 햇빛의 기운", 丁: "정화 · 오래 밝히는 불빛의 기운", 戊: "무토 · 든든한 산과 대지의 기운", 己: "기토 · 돌보고 가꾸는 흙의 기운", 庚: "경금 · 결단하고 다듬는 쇠의 기운", 辛: "신금 · 정교하게 빛나는 쇠의 기운", 壬: "임수 · 크게 흐르는 물의 기운", 癸: "계수 · 스며들고 적시는 물의 기운" };
const CHILD_BOND: Record<string, string> = { LOW: "천천히 가까워지는 편", MODERATE: "차분히 이어지는 편", STRONG: "깊게 이어지는 편", VERY_STRONG: "매우 깊게 이어지는 편" };
const PILLAR_LABEL: Record<PillarPosition, string> = { year: "년주", month: "월주", day: "일주", hour: "시주" };
const STEM_HANGUL: Record<string, string> = { 甲:"갑", 乙:"을", 丙:"병", 丁:"정", 戊:"무", 己:"기", 庚:"경", 辛:"신", 壬:"임", 癸:"계" };
const BRANCH_HANGUL: Record<string, string> = { 子:"자", 丑:"축", 寅:"인", 卯:"묘", 辰:"진", 巳:"사", 午:"오", 未:"미", 申:"신", 酉:"유", 戌:"술", 亥:"해" };
const pct = (value: number | null | undefined) => value == null ? "—" : `${value.toFixed(1)}%`;
const score = (value: number | null | undefined) => value == null ? "—" : `${Math.round(value)}%`;
const chapterSection = (report: StructuredInterpretation | null, id: string) => report?.sections.find((section) => section.id === id);

function Chapter({ number, id, title, headline, lead, children, tone = "paper" }: { number: string; id: string; title: string; headline: string; lead?: string; children: React.ReactNode; tone?: "paper" | "ink" | "wine" }) { return <section id={id} className={`lifetimeChapter ${tone}`}><div className="chapterRule"><span>{number}</span><i /></div><p className="chapterTitle">{title}</p><h2>{headline}</h2>{lead && <p className="chapterLead">{lead}</p>}{children}</section>; }
function AiCopy({ report, id, fallback }: { report: StructuredInterpretation | null; id: string; fallback: string[] }) { const section = chapterSection(report, id); const paragraphs = section?.paragraphs?.length ? section.paragraphs : section?.body ? [section.body] : fallback; return <div className="longCopy">{paragraphs.map((paragraph, index) => <p key={`${id}-${index}`}>{paragraph}</p>)}</div>; }
function Metric({ label, value, note, tone = "support" }: { label: string; value: string; note?: string; tone?: "support" | "activity" | "neutral" }) { return <div className={`lifetimeMetric ${tone}`}><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }
function CrowNote({ children }: { children: React.ReactNode }) { return <aside className="crowNote"><span aria-hidden="true">●</span><p><b>삼족오 한마디</b>{children}</p></aside>; }
function EvidenceDetails({ children }: { children: React.ReactNode }) { return <details className="chapterEvidence"><summary>왜 이렇게 보나요?</summary><div>{children}</div></details>; }
function EvidenceRows({ rows }: { rows: Array<[string,string]> }) { return <dl className="evidenceRows">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>; }

export function LifetimeReport({ analysis, current, relationshipStatus, interpretation, onRetry, onRestart }: { analysis: SajuAnalysis; current: CurrentPeriodSelection; relationshipStatus: RelationshipStatus; interpretation: InterpretationUiState; onRetry: () => void; onRestart: () => void }) {
  const report = interpretation.status === "completed" && interpretation.report.reportType === "LIFETIME_GENERAL" ? interpretation.report : null;
  const fortune = analysis.fortune as FortuneResult, wellness = analysis.wellness.status === "implemented" ? analysis.wellness as WellnessResult : null, children = analysis.childrenFortune.status === "implemented" ? analysis.childrenFortune as ChildrenFortuneResult : null;
  const categories = fortune.categories.status === "implemented" ? fortune.categories.daeun[0] : null;
  const adjusted = analysis.fiveElements.adjustedStrength.elements, useful = analysis.usefulGods.synthesis.status === "implemented" ? analysis.usefulGods.synthesis : null;
  const topElements = useful ? useful.elements.slice(0, 3) : [];
  return <div className="lifetimeReport"><Cover analysis={analysis} report={report} onRestart={onRestart} /><nav className="chapterNav" aria-label="평생사주 목차">{LIFETIME_REPORT_V2.sections.map((section) => <a key={section.id} href={`#chapter-${section.chapterNumber}`}>{section.chapterNumber}</a>)}</nav><main>
    <Chapter number="01" id="chapter-01" title="당신의 사주를 한눈에" headline={report?.headline ?? "내 삶의 큰 지도를 천천히 펼쳐봅니다"} lead={report?.summary ?? "타고난 기질과 평생의 큰 흐름을 계산 근거에 따라 한 권의 이야기로 정리했습니다."}><div className="overviewLines"><p><b>나를 대표하는 기운</b><span>{analysis.dayMaster ? STEM_COPY[analysis.dayMaster] : "분석 중"}</span></p><p><b>내가 힘을 쓰는 방식</b><span>{STRENGTH_COPY[analysis.strength.adjusted.level ?? ""] ?? "여러 힘의 균형을 살펴봅니다."}</span></p><p><b>삶에서 자주 만나는 질문</b><span>일과 관계에서 반복되는 선택의 기준을 중심으로 읽습니다.</span></p></div><EvidenceDetails><EvidenceRows rows={[["나를 대표하는 기운",analysis.dayMaster ?? "—"],["내가 힘을 쓰는 방식",`${analysis.strength.adjusted.score?.toFixed(1) ?? "—"} / 100`],["전문 기준",analysis.strength.adjusted.level ?? "—"]]}/></EvidenceDetails></Chapter>
    <Chapter number="02" id="chapter-02" title="나는 어떤 사람인가" headline={chapterSection(report,"personality")?.headline ?? "기준을 세우고, 내 방식으로 결과를 만들어 갑니다"}><AiCopy report={report} id="personality" fallback={[STRENGTH_COPY[analysis.strength.adjusted.level ?? ""] ?? "혼자 해내는 힘과 주변의 도움을 상황에 맞게 나누어 씁니다.", "한 가지 모습으로 단정하기보다 여러 기운과 삶의 구조를 함께 읽어야 나다운 선택이 선명해집니다."]}/><CrowNote>익숙한 장점은 당연하게 느껴져 놓치기 쉬워요. 반복해서 잘해 온 방식을 먼저 살펴보세요.</CrowNote><EvidenceDetails><p>첫인상과 속마음, 결정 방식은 대표 기운·힘의 균형·타고난 삶의 구조를 함께 읽었습니다.</p></EvidenceDetails></Chapter>
    <Chapter number="03" id="chapter-03" title="내 안의 다섯 기운" headline="자주 쓰는 힘과 아직 익숙하지 않은 힘이 있습니다"><AiCopy report={report} id="five-elements" fallback={["평소 자주 쓰는 힘과 조금 덜 익숙한 힘을 살펴봅니다. 숫자가 높다고 더 좋은 사람이고, 낮다고 부족한 사람이라는 뜻은 아닙니다."]}/><div className="elementBars">{ELEMENTS.map((element) => <div key={element}><p><b>{customerElement(element)}</b><span>{ELEMENT_THEME[element]}</span><strong>{pct(adjusted?.[element].percentage)}</strong></p><i><span style={{ width: `${adjusted?.[element].percentage ?? 0}%` }} /></i></div>)}</div><EvidenceDetails><p>다섯 숫자를 모두 더하면 100%가 됩니다. 성격 점수가 아니라 다섯 기운이 얼마나 들어 있는지를 보여 주는 비율입니다.</p></EvidenceDetails></Chapter>
    <Chapter number="04" id="chapter-04" title="내가 힘을 쓰는 방식" headline={STRENGTH_COPY[analysis.strength.adjusted.level ?? ""] ?? "혼자 할 때와 도움을 받을 때의 차이를 살펴봅니다"}><AiCopy report={report} id="strength" fallback={["일을 혼자 하는 편이 더 쉬운지, 다른 사람의 도움을 받을 때 더 잘 풀리는지를 살펴봅니다."]}/><div className="centerPower"><span>내가 힘을 쓰는 방식</span><strong>{score(analysis.strength.adjusted.score)}</strong><p>성적이 아닙니다. 혼자 해내는 힘이 강한지, 다른 사람과 함께할 때 더 수월한지를 보여 주는 숫자입니다.</p></div><EvidenceDetails><EvidenceRows rows={[["계산된 숫자",`${analysis.strength.adjusted.score?.toFixed(1) ?? "—"} / 100`],["전문가가 부르는 이름",analysis.strength.adjusted.level ?? "—"]]}/></EvidenceDetails></Chapter>
    <Chapter number="05" id="chapter-05" title="타고난 강점과 약점" headline="잘하는 것도 지나치면 오히려 힘들 수 있습니다"><AiCopy report={report} id="strengths-and-cautions" fallback={["꼼꼼함처럼 좋은 점도 지나치면 걱정이 많아지고 시작이 늦어질 수 있습니다."]}/><div className="twoEditorial"><article><span>이럴 때 도움이 됩니다</span><p>{report?.highlights[0] ?? "할 일의 순서를 정하고 꾸준히 끝까지 이어갈 수 있습니다."}</p></article><article><span>이럴 때 힘들 수 있습니다</span><p>{report?.cautions[0] ?? "변화가 많을 때는 서두르지 말고 먼저 쉬는 시간과 중요한 일을 정하세요."}</p></article></div><EvidenceDetails><p>앞에서 본 힘의 크기와 다섯 기운을 함께 확인했습니다. 여러 곳에서 같은 특징이 보일 때만 이 장에 넣었습니다.</p></EvidenceDetails></Chapter>
    <Chapter number="06" id="chapter-06" title="재능과 일하는 방식" headline="일하는 방법을 스스로 고를 수 있을 때 더 잘합니다"><AiCopy report={report} id="talent-and-work" fallback={["일을 어떻게 시작하는지, 혼자 할 때와 함께할 때 무엇이 편한지 살펴봅니다.", "특정 직업이 맞다고 단정하지 않습니다. 어떤 환경에서 덜 지치고 더 잘하는지를 이야기합니다."]}/><CrowNote>잘하지만 금방 지치는 일도 있어요. 오래 해도 덜 힘든 방법을 찾아보세요.</CrowNote><EvidenceDetails><p>말하고 표현하는 힘, 책임지는 힘, 배우는 힘, 돈과 결과를 다루는 모습을 함께 살펴봤습니다.</p></EvidenceDetails></Chapter>
    <WealthChapter report={report} category={categories} />
    <Chapter number="08" id="chapter-08" title="사랑과 인간관계" headline={chapterSection(report,"relationship")?.headline ?? (LIFETIME_REPORT_V2.relationship[relationshipStatus].label + "인 지금, 관계에서 중요한 것")}><p className="relationshipContext">{RELATIONSHIP_COPY[relationshipStatus]}</p><AiCopy report={report} id="relationship" fallback={RELATIONSHIP_DETAIL[relationshipStatus]}/>{categories && <EvidenceDetails><EvidenceRows rows={[["관계 도움 흐름",score(categories.relationship.supportScore)],["관계 움직임",score(categories.relationship.activityScore)],["현재 문맥",LIFETIME_REPORT_V2.relationship[relationshipStatus].label]]}/><p>도움의 정도와 변화의 크기는 서로 다른 지표입니다.</p></EvidenceDetails>}</Chapter>
    <ChildrenChapter report={report} children={children} />
    <WellnessChapter report={report} wellness={wellness} />
    <Chapter number="11" id="chapter-11" title="나에게 도움이 되는 기운" headline={chapterSection(report,"helpful-elements")?.headline ?? "막혔을 때 다른 방법을 찾으면 일이 더 잘 풀립니다"}><AiCopy report={report} id="helpful-elements" fallback={["이 숫자는 성공할 확률이 아닙니다. 일이 막혔을 때 어떤 방법을 쓰면 조금 더 쉽게 풀리는지를 보여 줍니다."]}/><div className="helpfulRanks">{topElements.map((row) => <article key={row.element}><span>{customerElement(row.element)}</span><strong>{score(row.score)}</strong><small>도움이 되는 정도 · {SUPPORT[row.role] ?? "참고"}</small></article>)}</div><EvidenceDetails><p>전문가들이 서로 다른 방법으로 계산한 결과를 한데 모았습니다. 자세한 계산은 18장에서 볼 수 있습니다.</p></EvidenceDetails></Chapter>
    <Chapter number="12" id="chapter-12" title="특별하게 타고난 특징" headline="눈에 띄는 특징도 삶 전체를 단정하지는 않습니다"><AiCopy report={report} id="special-features" fallback={["사람의 시선을 끄는 방식, 혼자 깊이 파고드는 힘, 감각이 예민하게 작동하는 부분을 생활 언어로 살펴봅니다.", "전통 별의 이름 하나만으로 길흉이나 사건을 정하지 않습니다."]}/><EvidenceDetails><p>귀인과 신살의 전문 이름과 근거는 18장 전문 분석실에서만 자세히 보여 줍니다.</p></EvidenceDetails></Chapter>
    <Chapter number="13" id="chapter-13" title="내 안의 여러 모습" headline="책임지는 나와 배우는 나는 같은 자리에서 나오지 않습니다"><AiCopy report={report} id="inner-roles" fallback={["경쟁할 때, 표현할 때, 책임을 맡을 때, 돈을 다룰 때, 배울 때의 모습은 서로 다를 수 있습니다.", "한 모습만 진짜라고 고르기보다 상황마다 어떤 역할이 먼저 나오는지를 읽습니다."]}/><EvidenceDetails><p>비견·겁재·식신·상관 등 십성 분류는 이 장의 숨은 전문 근거입니다. 자세한 명칭은 18장에서 확인할 수 있습니다.</p></EvidenceDetails></Chapter>
    <Chapter number="14" id="chapter-14" title="인생의 큰 흐름" headline="배우는 때와 직접 해내는 때가 번갈아 찾아옵니다"><AiCopy report={report} id="lifetime-flow" fallback={["어떤 때는 준비하고 배우는 일이 중요합니다. 또 어떤 때는 배운 것을 직접 보여 주는 일이 중요해집니다."]}/><CrowNote>도움을 많이 받는 때와 바쁘게 변하는 때는 서로 달라요. 두 숫자를 따로 보세요.</CrowNote><EvidenceDetails><p>10년마다 달라지는 모습을 살펴보고, 인생 초반·중간·후반에 무엇이 중요해지는지 정리했습니다.</p></EvidenceDetails></Chapter>
    <DaeunChapter report={report} fortune={fortune} />
    <Chapter number="16" id="chapter-16" title="인생 초반 · 중반 · 후반" headline="초반에는 배우고, 중간에는 고르고, 후반에는 나눕니다"><AiCopy report={report} id="life-phases" fallback={["초반에는 여러 일을 겪으며 나에게 맞는 방법을 찾습니다. 중간에는 계속할 일과 그만둘 일을 고릅니다. 후반에는 배운 것을 다른 사람과 나누는 일이 중요해집니다.", "앞 장의 내용을 그대로 반복하지 않고, 나이대마다 달라지는 중요한 일을 설명합니다."]}/><EvidenceDetails><p>10개의 긴 시기를 초반·중간·후반 세 부분으로 나누어 살펴봤습니다. 실제 사건을 새로 만들어 넣지 않았습니다.</p></EvidenceDetails></Chapter>
    <Chapter number="17" id="chapter-17" title="평생 기억하면 좋은 것" headline="생각이 다 끝날 때까지 기다리지 말고, 작은 일부터 시작하세요" tone="wine"><AiCopy report={report} id="takeaways" fallback={["여러 장에서 계속 나온 특징만 마지막에 다시 모았습니다.", "힘든 때에는 먼저 준비하세요. 바쁜 변화가 생기면 가장 중요한 일부터 정하세요."]}/><CrowNote>사주가 결정을 대신해 주지는 않아요. 나를 이해하는 참고 자료로만 사용하세요.</CrowNote><EvidenceDetails><p>앞의 16개 장에서 두 번 이상 나온 내용만 골랐습니다.</p></EvidenceDetails></Chapter>
    <ProfessionalChapter analysis={analysis} report={report} />
    {interpretation.status === "failed" && <div className="interpretationFallback" role="alert"><p>AI 상세 해석을 불러오지 못했습니다. 계산된 평생사주 결과는 정상적으로 표시되고 있습니다.</p><button onClick={onRetry}>상세 해석 다시 시도</button></div>}
    {interpretation.status === "pending" && <div className="interpretationLoading" role="status">긴 해석을 정리하고 있습니다. 계산 결과는 먼저 읽을 수 있어요.</div>}
    <footer className="reportNotice">이 결과는 전통 명리의 경향을 계산 근거에 따라 풀어낸 참고 콘텐츠입니다. 특정 사건을 확정하거나 중요한 현실 판단을 대신하지 않습니다.</footer>
  </main></div>;
}

function Cover({ analysis, report, onRestart }: { analysis: SajuAnalysis; report: StructuredInterpretation | null; onRestart: () => void }) { return <header className="lifetimeCover"><div className="coverTop"><b>POSTPOST</b><button onClick={onRestart}>다시 입력</button></div><div className="coverOrnament" aria-hidden="true"><i/><i/><i/></div><p>평생사주</p><h1>{analysis.person.name}님의<br/>한 권의 사주책</h1><h2>{report?.headline ?? "타고난 나와 인생의 큰 흐름을 읽는 시간"}</h2><span>계산 근거를 쉬운 한국어로 풀어낸 평생 이야기</span></header>; }

function WealthChapter({ report, category }: { report: StructuredInterpretation | null; category: CategoryFortunePeriod | null }) { return <Chapter number="07" id="chapter-07" title="돈을 대하는 방식" headline={chapterSection(report,"money-style")?.headline ?? "큰돈을 한 번 노리기보다 꾸준히 벌고 지키는 편입니다"}><AiCopy report={report} id="money-style" fallback={["돈을 벌고 쓸 때 얼마나 조심하는지, 좋은 기회가 왔을 때 얼마나 빨리 움직이는지를 살펴봅니다.", "어느 해에 돈을 많이 번다고 예측하지 않습니다. 평소 돈을 다루는 습관만 이야기합니다."]}/>{category && <EvidenceDetails><EvidenceRows rows={[["돈을 벌 때 도움받기 쉬운 정도",score(category.wealth.supportScore)],["돈이 많이 나갈 수 있는 정도",score(category.wealth.expensePressure.score)]]}/><p>평생 돈 점수가 아닙니다. 지금 보고 있는 10년 시기를 설명할 때만 참고하는 숫자입니다.</p></EvidenceDetails>}</Chapter>; }

function ChildrenChapter({ report, children }: { report: StructuredInterpretation | null; children: ChildrenFortuneResult | null }) { if (!children) return null; return <Chapter number="09" id="chapter-09" title="아이와 맺는 인연" headline="아이를 대할 때는 작은 변화를 잘 살피고 꾸준히 챙깁니다"><AiCopy report={report} id="children" fallback={["부모가 된다면 아이를 얼마나 꼼꼼하게 챙기는지, 언제 지나치게 걱정할 수 있는지를 살펴봅니다.", ...children.strengths.slice(0,2).map(row=>row.text), ...children.attentionAreas.slice(0,1).map(row=>row.text)]}/><EvidenceDetails><div className="childrenOverview"><div><Metric label="아이와의 관계가 크게 드러나는 정도" value={score(children.bond.score)} note={CHILD_BOND[children.bond.level]}/><p className="metricMeaning">출산 가능성을 뜻하지 않습니다. 사주에서 아이와의 관계가 얼마나 많이 보이는지를 나타냅니다.</p></div><article><span>관심이 한두 아이에게 모이는지 보는 값</span><strong>{children.countTendency.label}</strong></article></div><div className="genderEnergy"><p className="metricMeaning">실제 아이의 성별을 맞히는 숫자가 아닙니다. 옛 사주에서 쓰는 두 가지 상징을 비교한 값입니다.</p><p><span>아들 쪽 상징</span><b>{pct(children.genderEnergy.sonPercent)}</b></p><i><span style={{width:`${children.genderEnergy.sonPercent}%`}}/></i><p><span>딸 쪽 상징</span><b>{pct(children.genderEnergy.daughterPercent)}</b></p></div></EvidenceDetails><p className="softDisclaimer">실제로 아이를 몇 명 낳는지, 아이의 성별이 무엇인지, 임신할 수 있는지를 예측하지 않습니다.</p></Chapter>; }

function WellnessChapter({ report, wellness }: { report: StructuredInterpretation | null; wellness: WellnessResult | null }) { if (!wellness) return null; return <Chapter number="10" id="chapter-10" title="내 몸이 힘을 쓰는 방식" headline={chapterSection(report,"wellness")?.headline ?? "일이 바빠도 잠과 식사 시간을 지켜야 덜 지칩니다"}><AiCopy report={report} id="wellness" fallback={[`평소 잘 유지되는 쪽은 ${wellness.strengths.map((element)=>customerElement(element)).join("·") || "전체"}이고, 조금 더 챙겨야 하는 쪽은 ${wellness.attentionAreas.map((element)=>customerElement(element)).join("·") || "생활 습관"}입니다.`, ...wellness.habits.slice(0,3).map(row=>row.guidance)]}/><EvidenceDetails><div className="wellnessBalance"><span>생활 습관이 고르게 잡힌 정도</span><strong>{score(wellness.constitutionalBalanceScore)}</strong></div><p className="metricIntro">건강 점수가 아닙니다. 잠, 식사, 움직임 같은 생활 습관을 돌아볼 때 참고하는 숫자입니다.</p><div className="wellnessElements">{ELEMENTS.map(element=><article key={element}><span>{customerElement(element)} 기운 <strong>{pct(wellness.elements[element].percentage)}</strong></span><b>{wellness.elements[element].theme}과 이어서 살펴보는 기운</b></article>)}</div></EvidenceDetails><p className="softDisclaimer">병을 알아보는 검사가 아닙니다. 전통 사주 방식으로 생활 습관을 돌아보는 참고 내용입니다.</p></Chapter>; }

function DaeunChapter({ report, fortune }: { report: StructuredInterpretation | null; fortune: FortuneResult }) { const periods=fortune.daeun.status==="implemented"?fortune.daeun.periods:[]; const [selected,setSelected]=useState(0); const active=periods[selected]??periods[0]; return <Chapter number="15" id="chapter-15" title="10년마다 바뀌는 나" headline="10년마다 도움받기 쉬운 정도와 바빠지는 정도가 달라집니다"><AiCopy report={report} id="daeun" fallback={["앞 시기에 쌓은 경험은 다음 시기에 선택할 때 도움이 됩니다. 한 시기만 보고 좋다거나 나쁘다고 판단하지 마세요."]}/><div className="periodIndicator" aria-live="polite"><b>{selected+1}</b><span>/ {periods.length}</span><i><span style={{width:`${periods.length ? ((selected+1)/periods.length)*100 : 0}%`}}/></i></div><div className="daeunRail" role="list" aria-label="10년 큰 흐름">{periods.map((period,index)=><button role="listitem" aria-pressed={index===selected} key={period.index} onClick={()=>setSelected(index)}><b>{STEM_HANGUL[period.pillar.stem]}{BRANCH_HANGUL[period.pillar.branch]}</b><span>{period.sourcePeriod.ageRange}</span><span>{period.sourcePeriod.startInstant?.slice(0,4)}~{period.sourcePeriod.endInstant?.slice(0,4)}</span><small>{period.pillar.stem}{period.pillar.branch}</small></button>)}</div>{active&&<div className="daeunFocus"><h3>{STEM_HANGUL[active.pillar.stem]}{BRANCH_HANGUL[active.pillar.branch]} · {active.sourcePeriod.ageRange}</h3><small className="hanjaSecondary">{active.pillar.stem}{active.pillar.branch}</small><p>{active.activation.level==="HIGH"||active.activation.level==="VERY_HIGH"?"맡은 일이나 생활 환경이 자주 바뀔 수 있는 시기입니다.":"큰 변화보다 지금 하는 일을 정리하기 쉬운 시기입니다."}</p><EvidenceDetails><div className="metricPair"><Metric label="도움받기 쉬운 정도" value={score(active.preference.baseFavorabilityScore)} note={SUPPORT[active.preference.role]??active.preference.role}/><Metric label="바빠지거나 바뀌는 정도" value={score(active.activation.score)} note={ACTIVITY[active.activation.level]??active.activation.level} tone="activity"/></div><EvidenceRows rows={[["전문가용 한자",`${active.pillar.stem}${active.pillar.branch}`]]}/><p>도움을 받는 것과 변화가 많은 것은 서로 다릅니다. 두 숫자를 합쳐 좋다거나 나쁘다고 말하지 않습니다.</p></EvidenceDetails></div>}</Chapter>; }

function ProfessionalChapter({ analysis, report }: { analysis:SajuAnalysis; report:StructuredInterpretation|null }) { const native=analysis.fiveElements.nativeStrength, adjusted=analysis.fiveElements.adjustedStrength.elements; return <section id="chapter-18" className="professionalRoom"><details><summary><span><small>18 · 전문 분석실</small><b>계산 근거와 전문 용어를 확인합니다</b></span><em>펼쳐 보기</em></summary><div className="professionalInner"><AiCopy report={report} id="professional" fallback={["기본 결과와 같은 원국, 규칙 버전, evidence를 사용합니다."]}/><h3>사주 원국</h3><div className="professionalPillars">{(["year","month","day","hour"] as PillarPosition[]).map(position=><article key={position}><span>{PILLAR_LABEL[position]}</span><b>{analysis.pillars[position].stem}{analysis.pillars[position].branch}</b><small>천간 십성: {analysis.tenGods.value?.heavenlyStems[position].korean}</small></article>)}</div><h3>오행 기본값과 관계 반영값</h3><div className="professionalElements">{ELEMENTS.map(element=><p key={element}><b>{customerElement(element,true)}</b><span>기본 {pct(native?.[element].percentage)}</span><span>관계 반영 {pct(adjusted?.[element].percentage)}</span></p>)}</div><h3>전문 분류</h3><p>{customerTerm("격국")}: {analysis.structure.primary?.type} · {customerTerm("용신")}: {analysis.usefulGods.synthesis.status==="implemented"?analysis.usefulGods.synthesis.elements.slice(0,3).map(row=>customerElement(row.element,true)).join(" · "):"판단 유보"}</p><details><summary>버전과 evidence IDs</summary><pre>{JSON.stringify({rulesetVersion:analysis.rulesetVersion,engineVersion:analysis.engineMetadata.engineVersion,evidence:analysis.daeun.evidence},null,2)}</pre></details></div></details></section>; }
