"use client";
import { useState } from "react";
import { customerElement, customerTerm } from "@/rules/customer-terminology.v1";
import { LIFETIME_REPORT_V2 } from "@/rules/lifetime-report.v2";
import type { RelationshipStatus, StructuredInterpretation } from "@/types/ai-interpretation";
import type { CurrentPeriodSelection, InterpretationUiState } from "@/types/customer-result";
import type { CategoryFortunePeriod } from "@/types/category-fortune";
import type { FortuneResult } from "@/types/fortune";
import type { SajuAnalysis, Element, PillarPosition } from "@/types/saju-analysis";
import type { WellnessResult } from "@/types/wellness";
import type { ChildrenFortuneResult } from "@/types/children-fortune";

const ELEMENTS: Element[] = ["wood", "fire", "earth", "metal", "water"];
const ELEMENT_THEME: Record<Element, string> = { wood: "성장과 유연함", fire: "표현과 추진", earth: "현실과 관리", metal: "기준과 정리", water: "생각과 회복" };
const RELATIONSHIP_COPY: Record<RelationshipStatus, string> = { SINGLE: "새로운 만남에서는 사람을 고르는 기준과 관계를 시작하는 방식을 먼저 살펴보세요.", DATING: "현재 관계에서는 표현과 소통, 갈등을 풀어 가는 방식이 중요합니다.", MARRIED: "배우자와 생활할 때는 역할과 책임, 오래 함께할수록 필요한 소통을 살펴보세요." };
const RELATIONSHIP_DETAIL: Record<RelationshipStatus, string[]> = {
  SINGLE:["새로운 사람을 만날 때는 빠른 호감보다 말과 행동이 오래 일치하는지를 살핍니다.","처음에는 감정을 크게 드러내지 않지만 신뢰가 생기면 행동으로 꾸준히 마음을 보여 줍니다.","서로의 독립성을 존중하면서 필요한 순간에 분명히 연결되는 관계가 편안합니다.","상대가 알아서 이해하기를 기다리기보다 내 기대와 관계의 속도를 말로 알려 주는 것이 도움이 됩니다."],
  DATING:["연애 중에는 애정의 크기보다 서로 다른 표현 방식을 이해하는 일이 중요합니다.","갈등이 생기면 생각을 정리한 뒤 말하려는 편이라, 침묵의 이유와 필요한 시간을 먼저 알려 주는 것이 좋습니다.","장기적인 관계로 갈수록 약속과 생활 리듬, 현실적인 역할 분담이 신뢰의 핵심이 됩니다.","정답을 정해 설득하기보다 상대의 관점을 확인한 뒤 함께 기준을 만드는 대화가 관계를 오래 지켜 줍니다."],
  MARRIED:["기혼 관계에서는 생활의 안정과 맡은 역할을 성실하게 지키는 모습이 먼저 드러납니다.","가족의 필요를 미리 살피는 장점이 있지만, 책임을 혼자 떠안으면 서운함이 늦게 쌓일 수 있습니다.","배우자와는 감정만 확인하기보다 일정·가사·재정처럼 현실적인 영역을 함께 조율할 때 관계가 편안해집니다.","오래 함께할수록 익숙함 속에서도 각자의 회복 시간과 새로운 대화 주제를 남겨 두는 것이 중요합니다."],
};
const STRENGTH_COPY: Record<string, string> = { 극약: "회복과 보충을 먼저 챙길 때 힘이 납니다.", 태약: "주변 자원과 좋은 환경을 활용할 때 힘이 납니다.", 신약: "도움을 연결하고 리듬을 지킬 때 강점이 살아납니다.", 중화신약: "균형에 가깝지만 주변의 도움을 함께 쓸 때 편안합니다.", 중화신강: "균형에 가깝고 스스로 움직이는 힘이 조금 더 분명합니다.", 신강: "스스로 정하고 밀고 가는 힘이 분명합니다.", 태강: "강한 추진력을 조절해서 쓰는 것이 중요합니다.", 극왕: "집중된 힘을 유연하게 나누어 쓰는 것이 중요합니다." };
const ACTIVITY: Record<string, string> = { LOW: "잔잔함", MODERATE: "보통", HIGH: "큰 편", VERY_HIGH: "매우 큰 편" };
const SUPPORT: Record<string, string> = { PRIMARY_FAVORABLE: "매우 우호적", STRONG_FAVORABLE: "우호적", FAVORABLE: "비교적 우호적", CONDITIONAL: "조건부", NEUTRAL: "중립적", CAUTION: "주의 필요", UNFAVORABLE: "부담이 있는 편", VERY_SUPPORTIVE: "매우 든든함", SUPPORTIVE: "든든함", MODERATELY_SUPPORTIVE: "다소 도움", MIXED: "여러 흐름이 섞임", LOW_SUPPORT: "도움이 적은 편", PRESSURED: "부담이 있는 편" };
const STEM_COPY: Record<string, string> = { 甲: "갑목 · 큰 나무의 기운", 乙: "을목 · 유연한 풀과 덩굴의 기운", 丙: "병화 · 밝은 햇빛의 기운", 丁: "정화 · 오래 밝히는 불빛의 기운", 戊: "무토 · 든든한 산과 대지의 기운", 己: "기토 · 돌보고 가꾸는 흙의 기운", 庚: "경금 · 결단하고 다듬는 쇠의 기운", 辛: "신금 · 정교하게 빛나는 쇠의 기운", 壬: "임수 · 크게 흐르는 물의 기운", 癸: "계수 · 스며들고 적시는 물의 기운" };
const CHILD_BOND: Record<string, string> = { LOW: "천천히 가까워지는 편", MODERATE: "차분히 이어지는 편", STRONG: "깊게 이어지는 편", VERY_STRONG: "매우 깊게 이어지는 편" };
const PILLAR_LABEL: Record<PillarPosition, string> = { year: "년주", month: "월주", day: "일주", hour: "시주" };
const STEM_HANGUL: Record<string, string> = { 甲:"갑", 乙:"을", 丙:"병", 丁:"정", 戊:"무", 己:"기", 庚:"경", 辛:"신", 壬:"임", 癸:"계" };
const BRANCH_HANGUL: Record<string, string> = { 子:"자", 丑:"축", 寅:"인", 卯:"묘", 辰:"진", 巳:"사", 午:"오", 未:"미", 申:"신", 酉:"유", 戌:"술", 亥:"해" };
const pct = (value: number | null | undefined) => value == null ? "—" : `${value.toFixed(1)}%`;
const score = (value: number | null | undefined) => value == null ? "—" : `${Math.round(value)}%`;
const chapterSection = (report: StructuredInterpretation | null, id: string) => report?.sections.find((section) => section.id === id);

function Chapter({ number, id, title, headline, lead, children, tone = "paper" }: { number: string; id: string; title: string; headline: string; lead?: string; children: React.ReactNode; tone?: "paper" | "ink" | "wine" }) { return <section id={id} className={`lifetimeChapter ${tone}`}><div className="chapterRule"><span>{number}</span><i /></div><p className="chapterTitle">{title}</p><h2>{headline}</h2>{lead && <p className="chapterLead">{lead}</p>}{children}</section>; }
function AiCopy({ report, id, fallback }: { report: StructuredInterpretation | null; id: string; fallback: string[] }) { const section = chapterSection(report, id); const paragraphs = section?.paragraphs?.length ? section.paragraphs : section?.body ? [section.body] : fallback; return <div className="longCopy">{paragraphs.map((paragraph, index) => <p key={`${id}-${index}`}>{paragraph}</p>)}</div>; }
function Metric({ label, value, note, tone = "support" }: { label: string; value: string; note?: string; tone?: "support" | "activity" | "neutral" }) { return <div className={`lifetimeMetric ${tone}`}><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }
function CrowNote({ children }: { children: React.ReactNode }) { return <aside className="crowNote"><span aria-hidden="true">●</span><p><b>삼족오 한마디</b>{children}</p></aside>; }

export function LifetimeReport({ analysis, current, relationshipStatus, interpretation, onRetry, onRestart }: { analysis: SajuAnalysis; current: CurrentPeriodSelection; relationshipStatus: RelationshipStatus; interpretation: InterpretationUiState; onRetry: () => void; onRestart: () => void }) {
  const report = interpretation.status === "completed" && interpretation.report.reportType === "LIFETIME_GENERAL" ? interpretation.report : null;
  const fortune = analysis.fortune as FortuneResult, wellness = analysis.wellness.status === "implemented" ? analysis.wellness as WellnessResult : null, children = analysis.childrenFortune.status === "implemented" ? analysis.childrenFortune as ChildrenFortuneResult : null;
  const categories = fortune.categories.status === "implemented" ? fortune.categories.daeun[0] : null;
  const adjusted = analysis.fiveElements.adjustedStrength.elements, useful = analysis.usefulGods.synthesis.status === "implemented" ? analysis.usefulGods.synthesis : null;
  const topElements = useful ? useful.elements.slice(0, 3) : [];
  return <div className="lifetimeReport"><Cover analysis={analysis} report={report} onRestart={onRestart} /><nav className="chapterNav" aria-label="평생사주 목차">{LIFETIME_REPORT_V2.sections.map((section) => <a key={section.id} href={`#chapter-${section.chapterNumber}`}>{section.chapterNumber}</a>)}</nav><main>
    <Chapter number="01" id="chapter-01" title="당신의 사주를 한눈에" headline={report?.headline ?? "내 삶의 큰 지도를 천천히 펼쳐봅니다"} lead={report?.summary ?? "타고난 기질과 평생의 큰 흐름을 계산 근거에 따라 한 권의 이야기로 정리했습니다."}><div className="overviewLines"><p><b>나를 대표하는 기운</b><span>{analysis.dayMaster ? STEM_COPY[analysis.dayMaster] : "분석 중"}</span></p><p><b>내가 힘을 쓰는 방식</b><span>{STRENGTH_COPY[analysis.strength.adjusted.level ?? ""] ?? "여러 힘의 균형을 살펴봅니다."}</span></p><p><b>타고난 삶의 구조</b><span>일과 관계에서 반복되는 기준을 중심으로 읽습니다.</span></p></div></Chapter>
    <Chapter number="02" id="chapter-02" title="나는 어떤 사람인가" headline={chapterSection(report,"personality")?.headline ?? "기준을 세우고, 내 방식으로 결과를 만들어 갑니다"}><AiCopy report={report} id="personality" fallback={[STRENGTH_COPY[analysis.strength.adjusted.level ?? ""] ?? "내 힘과 주변의 도움을 함께 활용합니다.", "한 가지 모습으로 단정하기보다 오행과 삶의 구조를 함께 읽어야 나다운 선택이 선명해집니다."]}/><CrowNote>익숙한 장점은 당연하게 느껴져 놓치기 쉬워요. 반복해서 잘해 온 방식을 먼저 살펴보세요.</CrowNote></Chapter>
    <Chapter number="03" id="chapter-03" title="내 안의 다섯 기운" headline="다섯 기운은 서로 다른 방식으로 나를 움직입니다"><div className="elementBars">{ELEMENTS.map((element) => <div key={element}><p><b>{customerElement(element)}</b><span>{ELEMENT_THEME[element]}</span><strong>{pct(adjusted?.[element].percentage)}</strong></p><i><span style={{ width: `${adjusted?.[element].percentage ?? 0}%` }} /></i></div>)}</div><AiCopy report={report} id="five-elements" fallback={["그래프는 관계를 반영한 대표 분포입니다. 숫자가 높다고 무조건 좋거나 낮다고 나쁜 것은 아닙니다."]}/></Chapter>
    <Chapter number="04" id="chapter-04" title="내가 힘을 쓰는 방식" headline={STRENGTH_COPY[analysis.strength.adjusted.level ?? ""] ?? "내 힘의 중심을 살펴봅니다"}><div className="centerPower"><span>중심 힘</span><strong>{score(analysis.strength.adjusted.score)}</strong><p>좋고 나쁨이 아니라, 스스로 밀고 가는 힘과 주변을 활용하는 힘의 상대적 위치입니다.</p></div><AiCopy report={report} id="strength" fallback={["상황에 따라 힘을 쓰는 방식을 조절하면 타고난 장점이 더 안정적으로 드러납니다."]}/></Chapter>
    <Chapter number="05" id="chapter-05" title="타고난 강점과 약점" headline="강점은 반복해서 쓰고, 부담은 미리 알아차립니다"><div className="twoEditorial"><article><span>강점</span><p>{report?.highlights[0] ?? "기준을 세우고 꾸준히 결과를 쌓는 힘을 활용할 수 있습니다."}</p></article><article><span>주의할 점</span><p>{report?.cautions[0] ?? "변화가 큰 시기에는 속도보다 회복과 우선순위를 먼저 확인하세요."}</p></article></div><AiCopy report={report} id="strengths-and-cautions" fallback={["같은 특징도 환경과 시기에 따라 장점과 부담으로 다르게 드러날 수 있습니다."]}/></Chapter>
    <Chapter number="06" id="chapter-06" title="재능과 일하는 방식" headline="내 재능은 익숙한 방식 속에서 가장 먼저 드러납니다"><AiCopy report={report} id="talent-and-work" fallback={["배움과 표현, 책임과 실행의 기운을 함께 살펴 나에게 맞는 일의 리듬을 찾습니다.", "빠른 결론보다 반복해서 잘해 온 과정에서 재능의 단서를 발견해 보세요."]}/><CrowNote>잘하는 일과 오래 할 수 있는 일은 다를 수 있어요. 에너지가 덜 소모되는 방식을 찾아보세요.</CrowNote></Chapter>
    <WealthChapter report={report} category={categories} />
    <Chapter number="08" id="chapter-08" title="사랑과 인간관계" headline={LIFETIME_REPORT_V2.relationship[relationshipStatus].label + "인 지금, 관계에서 중요한 것"}><p className="relationshipContext">{RELATIONSHIP_COPY[relationshipStatus]}</p><AiCopy report={report} id="relationship" fallback={RELATIONSHIP_DETAIL[relationshipStatus]}/>{categories && <div className="metricPair"><Metric label="관계 도움 흐름" value={score(categories.relationship.supportScore)} note={SUPPORT[categories.relationship.supportLevel] ?? categories.relationship.supportLevel}/><Metric label="관계 움직임" value={score(categories.relationship.activityScore)} note={ACTIVITY[categories.relationship.activityLevel] ?? categories.relationship.activityLevel} tone="activity"/></div>}</Chapter>
    <ChildrenChapter report={report} children={children} />
    <WellnessChapter report={report} wellness={wellness} />
    <Chapter number="11" id="chapter-11" title="나에게 도움이 되는 기운" headline="균형을 도와주는 기운을 생활 속에서 활용해 보세요"><div className="helpfulRanks">{topElements.map((row) => <article key={row.element}><span>{customerElement(row.element)}</span><strong>{score(row.score)}</strong><small>도움 흐름 · {SUPPORT[row.role] ?? "참고 흐름"}</small></article>)}</div><AiCopy report={report} id="helpful-elements" fallback={["이 수치는 성공 확률이 아니라 여러 용신 관점을 종합한 상대적 도움 흐름입니다."]}/></Chapter>
    <Chapter number="12" id="chapter-12" title="특별하게 타고난 특징" headline="눈에 띄는 특징도 삶 전체를 단정하지는 않습니다"><AiCopy report={report} id="special-features" fallback={["귀인과 신살은 성향과 흐름을 보조해서 읽는 전통 지표입니다. 하나의 이름만으로 길흉이나 사건을 확정하지 않습니다."]}/></Chapter>
    <Chapter number="13" id="chapter-13" title="내 안의 여러 모습" headline="상황마다 다른 역할도 모두 나의 일부입니다"><AiCopy report={report} id="inner-roles" fallback={["책임을 맡을 때, 배울 때, 경쟁할 때, 표현할 때의 모습은 서로 다를 수 있습니다.", "십성은 이 여러 모습을 분리해 이해하도록 돕는 전통적인 분류입니다."]}/></Chapter>
    <Chapter number="14" id="chapter-14" title="인생의 큰 흐름" headline="큰 흐름은 삶의 배경을 바꾸고, 선택은 그 안에서 이루어집니다"><AiCopy report={report} id="lifetime-flow" fallback={["평생 흐름은 한 번의 좋고 나쁨이 아니라 여러 시기가 이어지는 과정으로 읽습니다."]}/><CrowNote>변화가 큰 때와 도움이 많은 때는 같은 뜻이 아니에요. 두 축을 따로 확인하세요.</CrowNote></Chapter>
    <DaeunChapter report={report} fortune={fortune} />
    <Chapter number="16" id="chapter-16" title="인생 초반 · 중반 · 후반" headline="나이에 따라 삶에서 중요해지는 질문도 달라집니다"><AiCopy report={report} id="life-phases" fallback={["초반에는 기반과 경험, 중반에는 선택과 책임, 후반에는 축적한 것을 나누는 흐름을 중심으로 살펴봅니다.", "실제 사건을 정해 놓기보다 각 구간에서 어떤 힘을 활용하기 쉬운지 읽습니다."]}/></Chapter>
    <Chapter number="17" id="chapter-17" title="평생 기억하면 좋은 것" headline="내 사주를 잘 쓴다는 것은 나다운 리듬을 아는 일입니다" tone="wine"><AiCopy report={report} id="takeaways" fallback={["점수 하나보다 반복되는 방향을 기억하세요.", "도움이 적은 때에는 준비하고, 변화가 큰 때에는 선택의 기준을 분명히 하세요."]}/><CrowNote>사주는 결정을 대신하지 않아요. 내 선택을 더 잘 이해하기 위한 지도처럼 활용해 보세요.</CrowNote></Chapter>
    <ProfessionalChapter analysis={analysis} report={report} />
    {interpretation.status === "failed" && <div className="interpretationFallback" role="alert"><p>AI 상세 해석을 불러오지 못했습니다. 계산된 평생사주 결과는 정상적으로 표시되고 있습니다.</p><button onClick={onRetry}>상세 해석 다시 시도</button></div>}
    {interpretation.status === "pending" && <div className="interpretationLoading" role="status">긴 해석을 정리하고 있습니다. 계산 결과는 먼저 읽을 수 있어요.</div>}
    <footer className="reportNotice">이 결과는 전통 명리의 경향을 계산 근거에 따라 풀어낸 참고 콘텐츠입니다. 특정 사건을 확정하거나 중요한 현실 판단을 대신하지 않습니다.</footer>
  </main></div>;
}

function Cover({ analysis, report, onRestart }: { analysis: SajuAnalysis; report: StructuredInterpretation | null; onRestart: () => void }) { return <header className="lifetimeCover"><div className="coverTop"><b>POSTPOST</b><button onClick={onRestart}>다시 입력</button></div><div className="coverOrnament" aria-hidden="true"><i/><i/><i/></div><p>평생사주</p><h1>{analysis.person.name}님의<br/>한 권의 사주책</h1><h2>{report?.headline ?? "타고난 나와 인생의 큰 흐름을 읽는 시간"}</h2><span>계산 근거를 쉬운 한국어로 풀어낸 평생 이야기</span></header>; }

function WealthChapter({ report, category }: { report: StructuredInterpretation | null; category: CategoryFortunePeriod | null }) { return <Chapter number="07" id="chapter-07" title="돈을 대하는 방식" headline="돈은 결과이기 전에 선택과 관리의 습관입니다"><AiCopy report={report} id="money-style" fallback={["돈을 버는 방식, 지출과 확장의 성향, 현실적인 성과를 다루는 태도를 함께 살펴봅니다.", "평생총운에서는 특정 연도나 월의 돈 피크를 예측하지 않고 기본 성향과 큰 방향만 설명합니다."]}/>{category && <div className="metricPair"><Metric label="재물 도움 흐름" value={score(category.wealth.supportScore)} note={SUPPORT[category.wealth.supportLevel] ?? category.wealth.supportLevel}/><Metric label="지출 압력" value={score(category.wealth.expensePressure.score)} note="독립 지표" tone="activity"/></div>}</Chapter>; }

function ChildrenChapter({ report, children }: { report: StructuredInterpretation | null; children: ChildrenFortuneResult | null }) { if (!children) return null; return <Chapter number="09" id="chapter-09" title="아이와 맺는 인연" headline="부모 역할에서는 관계를 만드는 방식이 먼저 드러납니다"><div className="childrenOverview"><div><Metric label="자녀 인연" value={score(children.bond.score)} note={CHILD_BOND[children.bond.level]}/><p className="metricMeaning">출산 가능성이 아니라, 사주에서 자녀 관계 영역이 얼마나 선명하게 나타나는지를 보는 지수입니다.</p></div><article><span>자녀 수 경향</span><strong>{children.countTendency.label}</strong></article></div><div className="genderEnergy"><p className="metricMeaning">실제 태아 성별 확률이 아닌 전통 명리의 상징 비교입니다.</p><p><span>아들 쪽 상징 기운</span><b>{pct(children.genderEnergy.sonPercent)}</b></p><i><span style={{width:`${children.genderEnergy.sonPercent}%`}}/></i><p><span>딸 쪽 상징 기운</span><b>{pct(children.genderEnergy.daughterPercent)}</b></p></div><AiCopy report={report} id="children" fallback={["자녀와 관계를 맺을 때 표현과 기대, 보호와 자율 사이의 균형을 살펴봅니다.", ...children.strengths.slice(0,2).map(row=>row.text), ...children.attentionAreas.slice(0,1).map(row=>row.text)]}/><p className="softDisclaimer">실제 출산 수나 태아 성별을 의미하는 값이 아니며, 임신·출산 가능성을 예측하지 않습니다.</p></Chapter>; }

function WellnessChapter({ report, wellness }: { report: StructuredInterpretation | null; wellness: WellnessResult | null }) { if (!wellness) return null; return <Chapter number="10" id="chapter-10" title="내 몸이 힘을 쓰는 방식" headline="컨디션은 타고난 균형과 생활 리듬이 함께 만듭니다"><div className="wellnessBalance"><span>타고난 컨디션 균형</span><strong>{score(wellness.constitutionalBalanceScore)}</strong></div><p className="metricIntro">아래 비율은 건강 능력 점수가 아니라, 몸의 리듬을 해석할 때 참고하는 오행 구성입니다.</p><div className="wellnessElements">{ELEMENTS.map(element=><article key={element}><span>{customerElement(element)} 기운 <strong>{pct(wellness.elements[element].percentage)}</strong></span><b>{wellness.elements[element].theme}과 연결해서 보는 기운</b></article>)}</div><AiCopy report={report} id="wellness" fallback={[`상대적으로 안정적인 기운은 ${wellness.strengths.map((element)=>customerElement(element)).join("·") || "균형 영역"}이고, 관리하면 좋은 기운은 ${wellness.attentionAreas.map((element)=>customerElement(element)).join("·") || "생활 리듬"}입니다.`, ...wellness.habits.slice(0,3).map(row=>row.guidance)]}/><p className="softDisclaimer">전통 명리의 오행 관점에서 보는 생활·컨디션 참고 해석이며 의학적 진단이 아닙니다.</p></Chapter>; }

function DaeunChapter({ report, fortune }: { report: StructuredInterpretation | null; fortune: FortuneResult }) { const periods=fortune.daeun.status==="implemented"?fortune.daeun.periods:[]; const [selected,setSelected]=useState(0); const active=periods[selected]??periods[0]; return <Chapter number="15" id="chapter-15" title="10년마다 바뀌는 나" headline="열 개의 큰 구간을 한눈에 보고, 하나씩 펼쳐봅니다"><div className="periodIndicator" aria-live="polite"><b>{selected+1}</b><span>/ {periods.length}</span><i><span style={{width:`${periods.length ? ((selected+1)/periods.length)*100 : 0}%`}}/></i></div><div className="daeunRail" role="list" aria-label="10년 큰 흐름">{periods.map((period,index)=><button role="listitem" aria-pressed={index===selected} key={period.index} onClick={()=>setSelected(index)}><b>{STEM_HANGUL[period.pillar.stem]}{BRANCH_HANGUL[period.pillar.branch]}</b><span>{period.sourcePeriod.ageRange}</span><span>{period.sourcePeriod.startInstant?.slice(0,4)}~{period.sourcePeriod.endInstant?.slice(0,4)}</span><small>{period.pillar.stem}{period.pillar.branch}</small></button>)}</div>{active&&<div className="daeunFocus"><h3>{STEM_HANGUL[active.pillar.stem]}{BRANCH_HANGUL[active.pillar.branch]} · {active.sourcePeriod.ageRange}</h3><small className="hanjaSecondary">{active.pillar.stem}{active.pillar.branch}</small><div className="metricPair"><Metric label="도움 흐름" value={score(active.preference.baseFavorabilityScore)} note={SUPPORT[active.preference.role]??active.preference.role}/><Metric label="변화 움직임" value={score(active.activation.score)} note={ACTIVITY[active.activation.level]??active.activation.level} tone="activity"/></div><p>도움의 정도와 변화의 크기는 서로 다른 값입니다. 하나의 종합 점수로 합치지 않습니다.</p></div>}<AiCopy report={report} id="daeun" fallback={["각 구간은 삶의 배경이 바뀌는 큰 흐름을 보여주며, 실제 선택과 사건을 확정하지 않습니다."]}/></Chapter>; }

function ProfessionalChapter({ analysis, report }: { analysis:SajuAnalysis; report:StructuredInterpretation|null }) { const native=analysis.fiveElements.nativeStrength, adjusted=analysis.fiveElements.adjustedStrength.elements; return <section id="chapter-18" className="professionalRoom"><details><summary><span><small>18 · 전문 분석실</small><b>계산 근거와 전문 용어를 확인합니다</b></span><em>펼쳐 보기</em></summary><div className="professionalInner"><AiCopy report={report} id="professional" fallback={["기본 결과와 같은 원국, 규칙 버전, evidence를 사용합니다."]}/><h3>사주 원국</h3><div className="professionalPillars">{(["year","month","day","hour"] as PillarPosition[]).map(position=><article key={position}><span>{PILLAR_LABEL[position]}</span><b>{analysis.pillars[position].stem}{analysis.pillars[position].branch}</b><small>천간 십성: {analysis.tenGods.value?.heavenlyStems[position].korean}</small></article>)}</div><h3>오행 기본값과 관계 반영값</h3><div className="professionalElements">{ELEMENTS.map(element=><p key={element}><b>{customerElement(element,true)}</b><span>기본 {pct(native?.[element].percentage)}</span><span>관계 반영 {pct(adjusted?.[element].percentage)}</span></p>)}</div><h3>전문 분류</h3><p>{customerTerm("격국")}: {analysis.structure.primary?.type} · {customerTerm("용신")}: {analysis.usefulGods.synthesis.status==="implemented"?analysis.usefulGods.synthesis.elements.slice(0,3).map(row=>customerElement(row.element,true)).join(" · "):"판단 유보"}</p><details><summary>버전과 evidence IDs</summary><pre>{JSON.stringify({rulesetVersion:analysis.rulesetVersion,engineVersion:analysis.engineMetadata.engineVersion,evidence:analysis.daeun.evidence},null,2)}</pre></details></div></details></section>; }
