import type { CalibrationTrace } from "@/types/calibration-trace";

const escapeHtml = (value: string) => value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const json = (value: unknown) => escapeHtml(JSON.stringify(value, null, 2));
const compact=(value:unknown):unknown=>Array.isArray(value)&&value.length>24?{totalItems:value.length,first:value.slice(0,8).map(compact),last:value.slice(-3).map(compact),notice:"전체 값은 .trace.json에서 확인"}:value&&typeof value==="object"?Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,row])=>[key,compact(row)])):value;

export function renderCalibrationTraceHtml(trace: CalibrationTrace) {
  const passed = trace.reconstruction.filter((row)=>row.status==="PASS").length, failed = trace.reconstruction.filter((row)=>row.status==="FAIL").length;
  const sections = trace.steps.map((step)=>`<details${step.index<=4?" open":""}><summary><span>${String(step.index).padStart(2,"0")}</span><b>${escapeHtml(step.title)}</b><em>${escapeHtml(step.status)}</em></summary><div class="body">
    <h3>입력 → 계산 → 결과</h3><div class="triple"><section><h4>입력</h4><pre>${json(compact(step.input))}</pre></section><section><h4>중간값·기여</h4><pre>${json(compact({rules:step.appliedRules,versions:step.ruleVersions,coefficients:step.coefficients,contributions:step.contributions,evidenceIds:step.evidenceIds}))}</pre></section><section><h4>결과</h4><pre>${json(compact(step.output))}</pre></section></div>
    ${step.reconstructionChecks.length?`<h4>재구성 검증</h4><pre>${json(step.reconstructionChecks)}</pre>`:""}</div></details>`).join("\n");
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(trace.caseId)} 계산 추적</title><style>
  :root{font-family:Pretendard,"Noto Sans KR","Apple SD Gothic Neo","Malgun Gothic",sans-serif;color:#201d1a;background:#f3eee6}body{max-width:1500px;margin:auto;padding:32px}header{padding:28px;color:#fff;background:#421b1c;border-radius:18px}header p{margin:8px 0 0;color:#e8cab0}.stats{display:flex;gap:10px;margin:18px 0}.stats span{padding:8px 12px;background:#fff;border-radius:99px}details{margin:12px 0;background:#fff;border:1px solid #ddd2c4;border-radius:14px}summary{display:grid;grid-template-columns:48px 1fr auto;gap:10px;align-items:center;min-height:58px;padding:0 18px;cursor:pointer}summary span{color:#7b2e2d;font-weight:800}summary em{color:#6c645d;font-size:12px}.body{padding:0 18px 20px;border-top:1px solid #eee5db}.triple{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.triple section{min-width:0}h4{color:#6d2928}pre{max-height:480px;overflow:auto;padding:14px;color:#e9e4dc;background:#25221f;border-radius:10px;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:800px){body{padding:12px}.triple{grid-template-columns:1fr}summary{grid-template-columns:38px 1fr}.body{padding:0 12px 14px}}
  </style></head><body><header><small>POSTPOST · TRACE / AUDIT v1</small><h1>${escapeHtml(trace.caseId)}</h1><p>계산식을 변경하지 않고 production 결과를 단계별로 재구성한 local audit 문서입니다.</p></header><div class="stats"><span>41단계</span><span>재구성 통과 ${passed}</span><span>실패 ${failed}</span></div>${sections}</body></html>`;
}
